### ISSUE TITLE
Portainer Installation Possible?

### ISSUE THREAD

**Issue by VeniceNerd** [tsightler/ring-mqtt#337] opened 2022-03-20 11:17 UTC
Hi! I'm wondering if it is possible to install ring-mqtt in Portainer (running on a Pi4). Usually I find my repositories for Portainer here: https://hub.docker.com/u/linuxserver but I have never installed anything on Portainer that I wasn't able to find there.

Any insight would be greatly appreciated!

**Comment by tsightler** [comment] 2022-03-20 13:29
@VeniceNerd I feel like this question is better asked on some Portainer community site vs here.  While I've played with Portainer in the past, I don't use it for anything personally and know very little about it.  I know that it can install any container from any supported registry, including Docker Hub, and this image is available in Docker Hub, so I don't see why not.  A quick Google provides instructions on how to [add a new contianer, including searching Docker Hub](https://docs.portainer.io/v/ce-2.11/user/docker/containers/add) so you should be able to just search for "ring-mqtt:latest" exactly like shown there and it should work.  However, since I have zero experience with Portainer, I won't likely be able to help more.

**Comment by tsightler** [comment] 2022-03-24 22:17
Closing this as it's not a bug in the project, but rather a general "how do I use Portainer" question which is not really something I can help with.

**Closed as completed by tsightler** 2022-03-24 22:17 UTC
Labels: support
