### ISSUE TITLE
Location disconnecting and not recovering until restart

### ISSUE THREAD

**Issue by nathanjskelton** [tsightler/ring-mqtt#223] opened 2021-08-13 22:09 UTC
I am running ring-mqtt in the docker container using compose... I am using it to feed HA and it's working well. Problem I am having is that reasonably often I get an error in the log (see below) and all of the devices go offline. The error seems to indicate a bad token, but it's transient: when I notice it, I restart ring-mqtt and everything comes back online.

I was thinking it might be nice, barring a solution, to have a healthcheck implemented in the container so that if the rest api fails and the devices go offline, I can restart it automatically with autoheal or something... thoughts?

```
o/state {"batteryLevel":96,"batteryStatus":"full","commStatus":"ok","lastCommTime":"2021-08-13T13:01:41Z","lastUpdate":"2021-08-13T13:01:41Z","linkQuality"
:"ok","tamperStatus":"ok"}
ring-mqtt        | (node:1) UnhandledPromiseRejectionWarning: Error: Refresh token is not valid.  Unable to authenticate with Ring servers.  See htt
ps://github.com/dgreif/ring/wiki/Refresh-Tokens
ring-mqtt        |     at RingRestClient.getGrantData (/app/ring-mqtt-docker/node_modules/ring-client-api/lib/api/rest-client.js:96:15)
ring-mqtt        |     at RingRestClient.<anonymous> (/app/ring-mqtt-docker/node_modules/ring-client-api/lib/api/rest-client.js:100:36)
ring-mqtt        |     at Generator.next (<anonymous>)
ring-mqtt        |     at /app/ring-mqtt-docker/node_modules/ring-client-api/lib/api/rest-client.js:8:71
ring-mqtt        |     at new Promise (<anonymous>)
ring-mqtt        |     at __awaiter (/app/ring-mqtt-docker/node_modules/ring-client-api/lib/api/rest-client.js:4:12)
ring-mqtt        |     at RingRestClient.getAuth (/app/ring-mqtt-docker/node_modules/ring-client-api/lib/api/rest-client.js:99:16)
ring-mqtt        |     at RingRestClient.<anonymous> (/app/ring-mqtt-docker/node_modules/ring-client-api/lib/api/rest-client.js:124:33)
ring-mqtt        |     at Generator.throw (<anonymous>)
ring-mqtt        |     at rejected (/app/ring-mqtt-docker/node_modules/ring-client-api/lib/api/rest-client.js:6:65)
ring-mqtt        | (node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an asy
nc function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise reject
ion, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
ring-mqtt        | 2021-08-13T14:58:06.316Z ring-mqtt Websocket for location id aec64f14-f4dc-48c1-4f33-121ab01e3775 is disconnected
ring-mqtt        | 2021-08-13T14:58:06.316Z ring-mqtt ring_topic/aec64f14-f4dc-48c1-4f33-121ab01e3775/alarm/4ce3b5fa-4a67-4f1d-a673-74927add6102/sta
tus offline
ring-mqtt        | 2021-08-13T14:58:06.316Z ring-mqtt ring_topic/aec64f14-f4dc-48c1-4f33-121ab01e3775/alarm/28a4aecf-0d04-41df-9e4d-9770b722c2ff/sta
tus offline
ring-mqtt        | 2021-08-13T14:58:06.316Z ring-mqtt ring_topic/aec64f14-f4dc-48c1-4f33-121ab01e3775/alarm/d74f8e19-16f9-4711-ac22-e032271d112b/sta
tus offline
ring-mqtt        | 2021-08-13T14:58:06.316Z ring-mqtt ring_topic/aec64f14-f4dc-48c1-4f33-121ab01e3775/alarm/8bf322be-78a0-420a-927d-a9f90bf9ed76/sta
tus offline
ring-mqtt        | 2021-08-13T14:58:06.316Z ring-mqtt ring_topic/aec64f14-f4dc-48c1-4f33-121ab01e3775/alarm/f253fcc3-d08a-4dbe-94e9-a8c1f09effd5/sta
tus offline
ring-mqtt        | 2021-08-13T14:58:06.316Z ring-mqtt ring_topic/aec64f14-f4dc-48c1-4f33-121ab01e3775/alarm/58572327-e599-4b41-8c6c-491df19d34ce/sta
tus offline
ring-mqtt        | 2021-08-13T14:58:06.316Z ring-mqtt ring_topic/aec64f14-f4dc-48c1-4f33-121ab01e3775/alarm/4f5e34d7-5116-4b7d-aead-babf31091e03/sta
tus offline

```

**Comment by tsightler** [comment] 2021-08-14 00:58
The script already has all of these capabilities and has had them from the start, it monitors the websocket for hub based devices (alarm and smart lighting) and uses a heartbeat on the polling for non-socket based devices like cameras and it will recover from the vast majority of errors, although you may still see unhandled promise rejections that happen at code levels below mine that I can't do much about.

However, it's not possible to recover from all issues automatically, for example, the error in the issue above is:

` Refresh token is not valid.  Unable to authenticate with Ring servers.  See https://github.com/dgreif/ring/wiki/Refresh-Tokens`

If the refresh token isn't valid, there app has no expectation that a retry would be useful, and retrying with an invalid token that won't authenticate is more likely to get you locked out than anything good happening.

Now, perhaps Ring servers are returning invalid token errors even when a token is valid, if you are saying that you are able to restart without doing any manual intervention such as reauthenticating to generate a new token, then that seems likely.  Ring has had quite a few server problems in the last week, although they've really only noted it on their status page on the 7th., but the problems have existed, to an extent, all week, and they've surfaced even in their own apps.

For example, twice this week, the Ring app on my phone got into a similar state as what you are noting above, the app thought it had a valid token so it would open and try to connect but fail saying unauthorized, but it also wouldn't let me reauthenticate even if I completely closed the app or even rebooted the phone.  I eventually had to navigate through the errors to the account page and force sign-out there, which removed the token completely and then it let me re-authenticate to generate a new one.

I have considered implementing a process supervisor for the container, something like S6, but I don't think it would have helped in your situation above since an authentication error would be considered a hard failure, not a restartable failure.

**Comment by tsightler** [comment] 2021-08-17 04:33
As I don't know what to do with this I'm closing this for now.  I believe the issue is on the Ring side as even the Ring app is experiencing similar issues and the Ring status page continues to show performance degradation for the iOS/Andriod apps (stated when they pushed out API changes a few weeks ago).

If it continues to be a problem I'll consider other possible options in the future, but as this project has been around for years and this is only recently an issue that seemed to coincide with changes on Ring's side, I'm going to assume they will eventually iron out these issues.

**Closed as completed by tsightler** 2021-08-17 04:33 UTC

**Comment by nathanjskelton** [comment] 2021-08-17 12:36
What I ended up doing here is polling the home assistant API for the status of the ring alarm. When it goes to unavailable, I restart ring-mqtt. This works as a catchall to handle any unrecoverable situation that occurs, including when home assistant restarts and seemingly I need to restart the script to get it to start working again. This works well for me, but ideally there would be a Docker health check script within the ring-MQTT container itself which would cause it to report itself as healthy or unhealthy, allowing an external process to restart it if need be.

**Comment by tsightler** [comment] 2021-08-17 15:17
If you have to restart the script when you restart Home Assistant then you have something unusual like perhaps not having birth/last will messages configured in the Home Assistant MQTT integration, or maybe using a custom path for birth/last will vs the standard as the script already listens for those status messages from Home Assistant to know to resend configuration data.  It will log a message when it sees the online state from Home Assistant and will send updated discovery 30 seconds later (this is to give time for Home Assistant to be ready as it's sometimes a little optimistic with it's "online" message).

The issue with using a "health check script" is that there is nothing wrong with the script in the scenario outlined above, the script is still running just fine, it's just lost authentication to Ring and thus taken the devices offline, which is still a completely valid status for the script and is even a normal situation in some cases.  For example, when running the addon, a user may revoke the token by changing the account password or deleting the associated authorized device in the Ring Control Panel.  This will cause the exact same error message you are seeing above, as it should, but the script/container is still fully functional, and it's still possible for the user to leverage the web UI to generate a new authentication token and the script will reconnect to Ring and continue on.

For the Docker standalone use case there's currently no way to recover from a loss of a valid token since the standalone docker version does not run the web UI component.  I simply never anticipated the possibility that Ring servers would return invalid token for a token that is in fact valid, so there's currently no retry logic if Ring reports the token invalid, no amount of monitoring outside of the script would change this.
