### ISSUE TITLE
Ring light duration defaulting to 1 minute

### ISSUE THREAD

**Issue by Farrell-terry** [tsightler/ring-mqtt#160] opened 2021-04-12 23:57 UTC
Not sure if anyone else is seeing this but my Ring light automation was working perfectly and then seemed to not work.  In reality, the automation worked but it seems Ring has the light duration defaulting to 1 minute.  You can change it for the Ring App, but that does not seem to translate to this integration. Plus their does not seem to be an option to set a duration.

Any thoughts or similar issue?

**Comment by tsightler** [comment] 2021-04-13 01:01
This sounds like expected behavior.  If you turn on the light with the light group it will always be 60 seconds because that is the Ring default duration for a light group.  If you turn on the light directly rather than via the group, it should honor the duratation that's the same as the last duration the light was turned on for in the Ring app. 

I have considered making this configurable, however, the default behavior seems OK for most people since it's been that way since day one and you are pretty much the first person to ever mention it.  Also I don't use Ring lighting myself and currently have no plans to, and it's not so easy to code up features that you really have no way to test.

**Comment by Farrell-terry** [comment] 2021-04-14 03:05
Hmmm...it is strange that the automation was working fine for me and not turning off after 1 minute but now has that is the behavior.  So you think that this is always the case?  Maybe I am not explaining the issues properly but unless the integration can tell Ring Light to stay on longer than a minute, I am not sure how useful it is for anyone.

**Comment by tsightler** [comment] 2021-04-14 17:08
I can't verify the behavior since I don't have Ring lighting, however, the expected behavior is that light groups would turn on for 60 seconds, but individual lights would turn on for whatever duration they were last turned on with the Ring app.  Basically, the code just sends the command to turn on the light without a duration so it uses whatever default that Ring uses for that entity.

I never knew how useful it was either, but nobody has ever complained about the current functionality and it's unchanged from the initial implementation which was tested by many users.  If it's not useful for you feel free to implement duration control and submit a PR.

**Comment by Farrell-terry** [comment] 2021-04-14 17:34
Understood.  I appreciate your work on this as the integration has been very helpful alleviating the deficiency's with Ring Alarm.

**Comment by tsightler** [comment] 2021-04-14 18:06
BTW, as I said above, controlling duration is on my to-do list, but, sadly, it's a pretty long list.  However, a really simply option I could hack up easily is to allow defining a default duration in the config for all smart lights controlled by the integration (this is what the ring-homebridge addon does).  Would this be sufficient?  If so, I can try to squeeze that in to the next release.  I need to get a new version out due to an upstream API change anyway.

Also, sorry for the accidental closure there, guess I was getting aggressive with the button.  I'll reopen if you think the above option would be good enough for a quick fix.

**Comment by tsightler** [comment] 2021-04-30 02:52
Decided to reopen this as I noticed that Home Assistant recently added a [Number MQTT integration](https://www.home-assistant.io/integrations/number.mqtt/) that I think would be suitable for setting light duration.  May be a few weeks before I get to work on this, but at least it seems like a good option.

**Comment by tsightler** [comment] 2021-07-16 03:07
So I think I'm finally shaking loose a little bit of time to work on ring-mqtt again and I'd like to take a stab at implementing some of the backlog of features and this is one of them, however, as I don't have any Ring lighting, I would need someone that does have Ring smart lighting that would be willing to test development releases with the 'duration" feature.  Anyone out there willing to help?

**Comment by jeffgraham-hub** [comment] 2021-07-16 22:01
I will do what I can to help. I use the ha-addon and my ring spotlights are battery powered if that makes a difference.

**Comment by tsightler** [comment] 2021-07-17 02:12
OK, thanks for the offer!  I've been busy converting the volume controls and snapshot duration features to use the number integration since that's actual things that I have.  That gives me some experience with the integration so I know what works and I hope that means I'll be able to code of duration without too many mistakes.  If things go well I'm going to try to code up light duration support this weekend and push it to the dev branch so it can be tested easily.

**Comment by tsightler** [comment] 2021-07-17 15:54
I have pushed my first attempt at this feature to the dev branch.  To test it, simply make sure you are on the latest version of the ring-mqtt addon (4.5.7), go to the configuration tab and change the "branch" option from "addon" to "dev", then restart the addon when prompted.  This will automatically pull in the latest dev branch each time the addon starts.  To revert back to the stable version simply change the option back to "addon".

How it works:

The default behavior should be the same as previous, so you might want to start with just making sure everything still works as it always did in case I managed to break that somehow (I made quite a few changes to the initialization function hoping to simplify the code and remove some redundancy).

To set duration for an individual light/group there is now a new number entity exposed for each device.  For example, if you have a light entity named "Backyard Spotlight", then there will be a corresponding number entity named "Backyard Spotlight Duration".  You can set this value via Home Assistant (either the UI or automation) to any value between 0 and 32767 (a little over 9 hours, seems to be the max the Ring API allows).  Once set, turning on the light should leave it on for the configured duration.

Right now restarting the addon will always cause lights to be in "auto" mode (duration = 0), but when I push this version to production I plan to include an option to allows setting the default duration for smart lighting for all lights, which will then be able to be overridden with automations for individual lights.

Anyone who is interested please test when you have a chance and let me know the results.

Please note that the dev branch has some other changes ongoing so you may not want to run it other than for testing this feature.  For example, volume controls have also been moved to number entities and are now enabled by default. 
 Previously volume controls were presented as "lights" because it was the only control available via the HA MQTT integration that included an way to set a number value, but this caused issues with some people's automations so volume control was disabled by default).  Also, fan and light controls are in the process of being updated to conform to the latest changes made to HA over the last months so things there aren't 100% stable right now.

Thanks again to all testers!

**Comment by jeffgraham-hub** [comment] 2021-07-18 17:50
It doesn't appear to be working. I never get the "Duration Enity".  I do show tht it is loading the dev version. I am having issues capturing the logs using the method I have used previously and that you outline in GET-LOGS.md. I will continue to try and get them as I assume you will need the to troubleshoot.

`-------------------------------------------------------
| Ring Device Integration via MQTT                    |
| Addon for Home Assistant                            |
|                                                     |
| Report issues at:                                   |
| https://github.com/tsightler/ring-mqtt-hassio-addon |
-------------------------------------------------------
Updating ring-mqtt to the development version...
Cloning into 'ring-mqtt-dev'...
Installing node module dependencies, please wait...
-------------------------------------------------------
ring-mqtt.js version 4.6.0-dev
Node version v14.17.3
NPM version 6.14.13
git version 2.26.3
-------------------------------------------------------
Using discovered MQTT Host: core-mosquitto
Using discovered MQTT Port: 1883
Using discovered MQTT User: addons
Using discovered MQTT password: <hidden>
-------------------------------------------------------
Running ring-mqtt...
`

**Comment by jeffgraham-hub** [comment] 2021-07-18 18:18
Here is the log.

[ring-mqtt.log](https://github.com/tsightler/ring-mqtt/files/6836754/ring-mqtt.log)

**Comment by tsightler** [comment] 2021-07-18 18:34
Thanks.  What's weird is that the logs clearly show the discovery information for the devices being sent and I don't see any obvious errors in the discovery packet. (edited to high full IDs):

```
2021-07-18T17:45:47.314Z ring-mqtt HASS config topic: homeassistant/number/xxxxxxxx-7916-4ae3-84fc-xxxxxxxx/xxxxxxxx-f4ba-4dd3-9724-xxxxxxxx_duration/config,
2021-07-18T17:45:47.315Z ring-mqtt {,
  message: {,
    name: 'West Side Floodlight Duration',,
    unique_id: 'xxxxxxxx-f4ba-4dd3-9724_xxxxxxx_duration',,
    availability_topic: 'ring/xxxxxxxx-7916-4ae3-84fc-xxxxxxxx/lighting/xxxxxxxx-f4ba-4dd3-9724-xxxxxxxx/status',,
    payload_available: 'online',,
    payload_not_available: 'offline',,
    state_topic: 'ring/xxxxxxxx-7916-4ae3-84fc-xxxxxxxx/lighting/xxxxxxxx-f4ba-4dd3-9724-xxxxxxxx/light/duration_state',,
    command_topic: 'ring/xxxxxxxx-7916-4ae3-84fc-xxxxxxxx/lighting/xxxxxxxx-f4ba-4dd3-9724-xxxxxxxx/light/duration_command',,
    min: 0,,
    max: 32767,,
    device: {,
      ids: [Array],,
      name: 'West Side Floodlight',,
      mf: 'Ring',,
      mdl: 'Lighting Switch/Light',
    },
  },
},
```

Could you check the Home Assistant log for any discovery errors?  Also, did you click on the device and does it really not show any additional entities there (a screenshot of a device would be useful).

**Comment by jeffgraham-hub** [comment] 2021-07-18 18:44
Here is the error from Home Assistant and a screenshot.

![Capture1](https://user-images.githubusercontent.com/65316307/126078726-2746e045-2364-481c-a296-ca1482255879.JPG)

`2021-07-18 12:42:04 ERROR (MainThread) [homeassistant.util.logging] Exception in async_discover when dispatching 'mqtt_discovery_new_number_mqtt': ({'message': {'name': 'West Side Floodlight Duration', 'unique_id': '0aafeae3-f4ba-4dd3-9724-b4087726f67b_duration', 'availability_topic': 'ring/fdd273b5-7916-4ae3-84fc-7d06510776ba/lighting/0aafeae3-f4ba-4dd3-9724-b4087726f67b/status', 'payload_available': 'online', 'payload_not_available': 'offline', 'state_topic': 'ring/fdd273b5-7916-4ae3-84fc-7d06510776ba/lighting/0aafeae3-f4ba-4dd3-9724-b4087726f67b/light/duration_state', 'command_topic': 'ring/fdd273b5-7916-4ae3-84fc-7d06510776ba/lighting/0aafeae3-f4ba-4dd3-9724-b4087726f67b/light/duration_command', 'min': 0, 'max': 32767, 'device': {'ids': ['0aafeae3-f4ba-4dd3-9724-b4087726f67b'], 'name': 'West Side Floodlight', 'mf': 'Ring', 'mdl': 'Lighting Switch/Light'}}, 'platform': 'mqtt'},)
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/mqtt/mixins.py", line 179, in async_discover
config = schema(discovery_payload)
File "/usr/local/lib/python3.9/site-packages/voluptuous/validators.py", line 218, in __call__
return self._exec((Schema(val) for val in self.validators), v)
File "/usr/local/lib/python3.9/site-packages/voluptuous/validators.py", line 341, in _exec
raise e if self.msg is None else AllInvalid(self.msg, path=path)
File "/usr/local/lib/python3.9/site-packages/voluptuous/validators.py", line 337, in _exec
v = func(v)
File "/usr/local/lib/python3.9/site-packages/voluptuous/schema_builder.py", line 272, in __call__
return self._compiled([], data)
File "/usr/local/lib/python3.9/site-packages/voluptuous/schema_builder.py", line 817, in validate_callable
return schema(data)
File "/usr/local/lib/python3.9/site-packages/voluptuous/schema_builder.py", line 272, in __call__
return self._compiled([], data)
File "/usr/local/lib/python3.9/site-packages/voluptuous/schema_builder.py", line 594, in validate_dict
return base_validate(path, iteritems(data), out)
File "/usr/local/lib/python3.9/site-packages/voluptuous/schema_builder.py", line 432, in validate_mapping
raise er.MultipleInvalid(errors)
voluptuous.error.MultipleInvalid: extra keys not allowed @ data['message']`

**Comment by tsightler** [comment] 2021-07-18 18:46
OK, digging just a little further, I do see an issue with the device ID in that discovery log, but I have no idea why as it's using the same variable for every discovery entry.  I need to dig into that I guess.

**Comment by jeffgraham-hub** [comment] 2021-07-18 18:51
The only difference I see in the logs for the duration entity is it is enclosed in message: {, } where the other entities aren't. However, that may be intentional.

**Comment by tsightler** [comment] 2021-07-18 19:03
Yep, I noticed that when looking at the id issue, it's not really an id issue, just an extra nested value.  It was really just a copy an paste error due to the fact that I use an inconsistent method to build the discovery message.  I probably should clean that up so I could more easily avoid a mistake like that in the future, but I've already pushed a fix that should address it if you try again.  Thanks very much, super useful!

**Comment by jeffgraham-hub** [comment] 2021-07-18 19:18
Still getting an error in HA logs.


```
2021-07-18 12:42:04 INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.mqtt
2021-07-18 12:42:04 ERROR (MainThread) [homeassistant.util.logging] Exception in async_discover when dispatching 'mqtt_discovery_new_number_mqtt': ({'message': {'name': 'West Side Floodlight Duration', 'unique_id': '0aafeae3-f4ba-4dd3-9724-b4087726f67b_duration', 'availability_topic': 'ring/fdd273b5-7916-4ae3-84fc-7d06510776ba/lighting/0aafeae3-f4ba-4dd3-9724-b4087726f67b/status', 'payload_available': 'online', 'payload_not_available': 'offline', 'state_topic': 'ring/fdd273b5-7916-4ae3-84fc-7d06510776ba/lighting/0aafeae3-f4ba-4dd3-9724-b4087726f67b/light/duration_state', 'command_topic': 'ring/fdd273b5-7916-4ae3-84fc-7d06510776ba/lighting/0aafeae3-f4ba-4dd3-9724-b4087726f67b/light/duration_command', 'min': 0, 'max': 32767, 'device': {'ids': ['0aafeae3-f4ba-4dd3-9724-b4087726f67b'], 'name': 'West Side Floodlight', 'mf': 'Ring', 'mdl': 'Lighting Switch/Light'}}, 'platform': 'mqtt'},)
```


```
-------------------------------------------------------,
| Ring Device Integration via MQTT                    |,
| Addon for Home Assistant                            |,
|                                                     |,
| Report issues at:                                   |,
| https://github.com/tsightler/ring-mqtt-hassio-addon |,
-------------------------------------------------------,
Updating ring-mqtt to the development version...,
Cloning into 'ring-mqtt-dev'...,
Installing node module dependencies, please wait...,
-------------------------------------------------------,
ring-mqtt.js version 4.6.0-dev,
Node version v14.17.3,
NPM version 6.14.13,
git version 2.26.3,
-------------------------------------------------------,
Using discovered MQTT Host: core-mosquitto,
Using discovered MQTT Port: 1883,
Using discovered MQTT User: addons,
Using discovered MQTT password: <hidden>,
-------------------------------------------------------,
Running ring-mqtt...,


2021-07-18T19:08:23.660Z ring-mqtt Publishing new device id: 0aafeae3-f4ba-4dd3-9724-b4087726f67b,
2021-07-18T19:08:23.661Z ring-mqtt HASS config topic: homeassistant/binary_sensor/fdd273b5-7916-4ae3-84fc-7d06510776ba/0aafeae3-f4ba-4dd3-9724-b4087726f67b/config,
2021-07-18T19:08:23.661Z ring-mqtt {,
  name: 'West Side Floodlight Motion',,
  unique_id: '0aafeae3-f4ba-4dd3-9724-b4087726f67b_motion',,
  availability_topic: 'ring/fdd273b5-7916-4ae3-84fc-7d06510776ba/lighting/0aafeae3-f4ba-4dd3-9724-b4087726f67b/status',,
  payload_available: 'online',,
  payload_not_available: 'offline',,
  state_topic: 'ring/fdd273b5-7916-4ae3-84fc-7d06510776ba/lighting/0aafeae3-f4ba-4dd3-9724-b4087726f67b/motion/state',,
  device_class: 'motion',,
  device: {,
    ids: [ '0aafeae3-f4ba-4dd3-9724-b4087726f67b' ],,
    name: 'West Side Floodlight',,
    mf: 'Ring',,
    mdl: 'Lighting Switch/Light',
  },
},
2021-07-18T19:08:23.661Z ring-mqtt HASS config topic: homeassistant/light/fdd273b5-7916-4ae3-84fc-7d06510776ba/0aafeae3-f4ba-4dd3-9724-b4087726f67b/config,
2021-07-18T19:08:23.662Z ring-mqtt {,
  name: 'West Side Floodlight Light',,
  unique_id: '0aafeae3-f4ba-4dd3-9724-b4087726f67b_light',,
  availability_topic: 'ring/fdd273b5-7916-4ae3-84fc-7d06510776ba/lighting/0aafeae3-f4ba-4dd3-9724-b4087726f67b/status',,
  payload_available: 'online',,
  payload_not_available: 'offline',,
  state_topic: 'ring/fdd273b5-7916-4ae3-84fc-7d06510776ba/lighting/0aafeae3-f4ba-4dd3-9724-b4087726f67b/light/state',,
  command_topic: 'ring/fdd273b5-7916-4ae3-84fc-7d06510776ba/lighting/0aafeae3-f4ba-4dd3-9724-b4087726f67b/light/command',,
  device: {,
    ids: [ '0aafeae3-f4ba-4dd3-9724-b4087726f67b' ],,
    name: 'West Side Floodlight',,
    mf: 'Ring',,
    mdl: 'Lighting Switch/Light',
  },
},
2021-07-18T19:08:23.662Z ring-mqtt HASS config topic: homeassistant/binary_sensor/fdd273b5-7916-4ae3-84fc-7d06510776ba/0aafeae3-f4ba-4dd3-9724-b4087726f67b/config,
2021-07-18T19:08:23.663Z ring-mqtt {,
  name: 'West Side Floodlight Duration',,
  unique_id: '0aafeae3-f4ba-4dd3-9724-b4087726f67b_duration',,
  availability_topic: 'ring/fdd273b5-7916-4ae3-84fc-7d06510776ba/lighting/0aafeae3-f4ba-4dd3-9724-b4087726f67b/status',,
  payload_available: 'online',,
  payload_not_available: 'offline',,
  state_topic: 'ring/fdd273b5-7916-4ae3-84fc-7d06510776ba/lighting/0aafeae3-f4ba-4dd3-9724-b4087726f67b/light/duration_state',,
  command_topic: 'ring/fdd273b5-7916-4ae3-84fc-7d06510776ba/lighting/0aafeae3-f4ba-4dd3-9724-b4087726f67b/light/duration_command',,,
,,
  max: 32767,,
  device: {,
    ids: [ '0aafeae3-f4ba-4dd3-9724-b4087726f67b' ],,
    name: 'West Side Floodlight',,
    mf: 'Ring',,
    mdl: 'Lighting Switch/Light',
  },
},
2021-07-18T19:08:23.663Z ring-mqtt HASS config topic: homeassistant/sensor/fdd273b5-7916-4ae3-84fc-7d06510776ba/0aafeae3-f4ba-4dd3-9724-b4087726f67b_info/config,
2021-07-18T19:08:23.663Z ring-mqtt {,
  name: 'West Side Floodlight Info',,
  unique_id: '0aafeae3-f4ba-4dd3-9724-b4087726f67b_info',,
  availability_topic: 'ring/fdd273b5-7916-4ae3-84fc-7d06510776ba/lighting/0aafeae3-f4ba-4dd3-9724-b4087726f67b/status',,
  payload_available: 'online',,
  payload_not_available: 'offline',,
  state_topic: 'ring/fdd273b5-7916-4ae3-84fc-7d06510776ba/lighting/0aafeae3-f4ba-4dd3-9724-b4087726f67b/info/state',,
  json_attributes_topic: 'ring/fdd273b5-7916-4ae3-84fc-7d06510776ba/lighting/0aafeae3-f4ba-4dd3-9724-b4087726f67b/info/state',,
  icon: 'mdi:information-outline',,
  value_template: '{{value_json["batteryLevel"]}}',,
  unit_of_measurement: '%',,
  device: {,
    ids: [ '0aafeae3-f4ba-4dd3-9724-b4087726f67b' ],,
    name: 'West Side Floodlight',,
    mf: 'Ring',,
    mdl: 'Lighting Switch/Light',
  },
},
```

**Comment by tsightler** [comment] 2021-07-18 19:25
Ah, pushing the discovery to the wrong topic, yet another copy/paste error.  I've got to be more careful with that.  I've run through it all again, and I think it's good now.

**Comment by jeffgraham-hub** [comment] 2021-07-18 20:19
The duration entity is now added to Home Assistant. Changing the duration has no impact though. Sorry, I am still struggling to get logs. Getting logs from the terminal as you outlined isn't working for me. Above I was using Portainer to get the logs but I can't seem to get it to copy the entire log. I will keep trying and get back to you.

**Comment by jeffgraham-hub** [comment] 2021-07-18 20:49
Ok, I found my issue with getting the logs.
Here is the time stamp where I made the change but the light still only came on for 60 seconds.

![tempsnip](https://user-images.githubusercontent.com/65316307/126081740-d2dfc97b-8df2-4856-9cd9-9af3c724dbb8.jpg)

`2021-07-18T20:37:48.756Z ring-mqtt ring/fdd273b5-7916-4ae3-84fc-7d06510776ba/lighting/0aafeae3-f4ba-4dd3-9724-b4087726f67b/light/duration_state 157`

**Comment by jeffgraham-hub** [comment] 2021-07-18 20:50
Helps if I attach the log....
[ring-mqtt.log](https://github.com/tsightler/ring-mqtt/files/6836932/ring-mqtt.log)

**Comment by tsightler** [comment] 2021-07-18 21:40
Well, I guess we're at least making progress.

Looking at the logs, I don't see anything obvious.  Clearly the update of the duration worked because the duration state is being reported as the set value, so that's good.  The code to turn on the light simply looks at this value and determines if it's >0 and, if so, includes it in the JSON data sent with the command to turn the light on.  There's just not much to go wrong here but I did just add a temporary debug string to output that data to the log before sending it hoping that might show me if there are any errors there.

Trying to think through what might be the issue, I also made a little tweak to always parse the duration value received via MQTT into an integer (MQTT raw values are always strings) as I thought the issue might be a type mismatch with the Ring API so if you could give it one more try hopefully it will either a) just work, or b) at least provide a little more insight into what is failing.

Thanks so much for the testing.  This is why it's so difficult to develop for something you don't have, just so many little things.  I'm sure a real developer would be far better at it!

**Comment by jeffgraham-hub** [comment] 2021-07-18 21:58
Same results...light comes on for 60 seconds regardless of duration.

[ring-mqtt.log](https://github.com/tsightler/ring-mqtt/files/6837005/ring-mqtt.log)

**Comment by tsightler** [comment] 2021-07-18 22:26
My debug failed, but I'm definitely running out of ideas here.  I've fixed the debug and added a function to conver the object to JSON before submitting it to the Ring API, but that's totally just a stab in the dark.  If that's not it, I'll have to spend some time researching this more.

To be clear, it is possible to actually set the duration for this light in the Ring app, right?

**Comment by jeffgraham-hub** [comment] 2021-07-18 22:33
To be honest I'm not sure about setting the duration via the Ring app but I will check. This isn't something I think I would use as I have my lights on a schedule to come on a sunset and stay on until morning. I was just trying to be helpful. I will get back to you in a couple of hours.

Jeff

________________________________

**Comment by tsightler** [comment] 2021-07-18 22:50
Thanks, no problems, I appreciate the testing.  I didn't really anticipate this type of issue as the code to set duration is basically ripped almost directly from the homebridge code so I just assumed that part would work without too much issue.  I expected the issues to be mostly around the discovery (as the earlier issues) and the command processing to set the duration, but that all seems to be working.

**Comment by jeffgraham-hub** [comment] 2021-07-19 01:15
So there is a setting in the Ring App for duration (see attached screenshot). I changed it to 10 minutes in the Ring app and then ran the data discovery to validate the field that changed {"onDuration":600}. 

This time the addon fails to turn on the lights. I reverted to 4.5.7 and I could turn on/off the lights. I did try reloading the dev version a second time and it wouldn't turn on the light.

[ring-mqtt.log](https://github.com/tsightler/ring-mqtt/files/6837268/ring-mqtt.log)

![Ring](https://user-images.githubusercontent.com/65316307/126088252-35dbb7b5-ca08-4e3e-aecd-d3ef59d01e42.jpg)

**Comment by tsightler** [comment] 2021-07-19 01:22
I'm not surprised that the last change broke it completely, but that's OK, the logs were still useful.  I can see now that there is something wrong with the logic that adds the duration, but I'm just not sure why.  I'm sure it's something silly on my part.

**Comment by tsightler** [comment] 2021-07-19 02:30
OK, I did some simulations with the homebridge code, just logging the JSON it produced, and compared it to my code, and I saw that the variable name was important which I somehow didn't notice before.  I've pushed one more version with this change and I believe that it should work.

I am curious about the "onDuration" value that you mentioned above, is that part of the data on the device (it's not listed in the ring-client-api type definitions)?  I'm thinking it might be a good idea to use that to set the initial duration.  My current planned implementation is to allow a config option that lets users define a default duration for all lights, but, if that's not defined, to just display 0, which means use last configured value.  However, if the onDuraiton is part of the data events, then I could use that to set the initial value and at least display what that automatically configured value is vs just displaying "0".

**Comment by jeffgraham-hub** [comment] 2021-07-19 17:04
Did a quick test before leaving the house and it appears to be working. Tested before making duration change and light stayed on for the 60 seconds set in the Ring App. Change duration in Home Assistant to 157 seconds and light stayed on for 157. Is there anything else you want me to test?

[ring-mqtt.log](https://github.com/tsightler/ring-mqtt/files/6842747/ring-mqtt.log)

2021-07-19T16:30:21.555Z ring-mqtt Lighting set data: {"lightMode":"on"}

2021-07-19T16:31:49.374Z ring-mqtt Received set light duration to 157 seconds for beams light: ac11a2e9-ff58-4950-a4d7-44f5a43ab3ec
2021-07-19T16:32:01.742Z ring-mqtt Lighting set data: {"lightMode":"on","duration":157}

Home Assistant log..
Turned off 11:34:39 AM 
Turned on 11:32:02 AM
Turned off 11:31:22 AM
Turned on 11:30:22 AM 

As far as the "onDuration" you see it defined when you due the data discovery [https://github.com/dgreif/ring/wiki/Data-Discovery](url)

`"name":"Garage Floodlight","pollInterval":0,"roomId":1,"setupByPluginStatus":"complete","setupByUserStatus":"unset","subCategoryId":0,"tags":[],"tamperStatus":"ok","zid":"ac11a2e9-ff58-uuid","autoShutoffTime":0,"batteries":[{"level":100,"status":"charged"}],"duskToDawnMode":"not-supported","glowStatus":"off","level":0.8,"lightMode":"on","lightSensorEnabled":true,"lightSensorThreshold":80,"lightSensorThresholdDefault":80,"lightStateChangeReason":"command","motionSensorEnabled":true,"motionStatus":"clear","on":true,"onDuration":157,"onUntil":1626713955128,"sensitivity":127,"sensitivityMin":255},{"adapterType":"ringnet","batteryStatus":"none","categoryId":0,"commStatus":"ok","commandTypes":{"identify":{"requiresTrust":false},"light-mode.set":{"requiresTrust":false}},"deviceFoundTime":1618263713646,"deviceType":"group.light-group.beams","impulseTypes":{"clear":{"trusted":false},"fault":{"trusted":false},"glow-status.glow":{"trusted":false},"glow-status.off":{"trusted":false},"light-mode.default":{"trusted":false},"light-mode.on":{"trusted":false},"light-mode.snooze":{"trusted":false},"switched.off":{"trusted":false},"switched.on":{"trusted":false}},"lastCommTime":0,"lastUpdate":1626694326064,"managerId":"ringnet","name":"Back Yard Floodlight`

**Comment by tsightler** [comment] 2021-07-19 17:48
I think that's it for now.  Thanks very much for all of the testing and thanks for the details about onDuration value.  In the final release of this feature the plan is to allow users to define a default duration for lights and light groups, but, if that's not defined, I think I'll default to whatever is in onDuration.  Out of curiosity, is onDuration available for light groups as well as the discovery data you posted appears to show part of a light and part of a group.

**Comment by jeffgraham-hub** [comment] 2021-07-19 18:04
Here is the complete output from data discovery.

[ring discovery.txt](https://github.com/tsightler/ring-mqtt/files/6843007/ring.discovery.txt)

**Comment by tsightler** [comment] 2021-07-20 20:35
Version 4.6.0 has been released and includes support for setting global default and individual duration for Ring Smart Lights.  Much thanks to @jeffgraham-hub for the testing!

**Closed as completed by tsightler** 2021-07-20 20:35 UTC
Labels: enhancement

**Comment by Farrell-terry** [comment] 2021-07-22 17:39
Thanks tsightler.  I will try it now.
