### ISSUE TITLE
WebRTC session disconnects almost immediately

### ISSUE THREAD

**Issue by juvenalandres** [tsightler/ring-mqtt#561] opened 2023-02-16 14:07 UTC
## Describe the problem
I've been having problems keeping the streams alive for a while now. They would die a few hours later I spun the container and never came back.  ```Deactivating live stream due to signal from RTSP server (no more active clients or publisher ended stream)```.
I've managed this problem with a script that restarted the container as soon as the message is detected in the logs.

Now I'm getting a different error, probably related to another package ring-mqtt is using, but still. No livestreams no snapshots.

## Describe your environment
```
Docker version 23.0.1
Debian 11
```

## Describe any steps you've taken to attempt to resolve the problem
Pull a new image
Restart the container

## Debug Logs
```
2023-02-16T13:58:40.397Z ring-rtsp [Front Door] Sending command to activate live stream ON-DEMAND
2023-02-16T13:58:40.398Z ring-mqtt [Front Door] Received set live stream state ON-DEMAND rtsp://localhost:8554/a03531c0a132d78dc2e1986d52bbc025
2023-02-16T13:58:40.398Z ring-mqtt [Front Door] ring/ad5195e5-48d9-4198-84d1-6893943d3f1a/camera/9c7613398876/stream/state ON
2023-02-16T13:58:40.399Z ring-attr [Front Door] ring/ad5195e5-48d9-4198-84d1-6893943d3f1a/camera/9c7613398876/stream/attributes {"status":"activating"}
2023-02-16T13:58:40.399Z ring-mqtt [Front Door] Initializing a live stream session for Ring cloud
2023-02-16T13:58:40.510Z ring-rtsp [Front Door] State indicates live stream is activating
2023-02-16T13:58:41.071Z ring-mqtt [Front Door] Live stream session successfully initialized, starting worker
2023-02-16T13:58:41.072Z ring-wrtc [Front Door] Live stream WebRTC worker received start command
2023-02-16T13:58:41.080Z ring-wrtc [Front Door] Live stream transcoding process is starting
2023-02-16T13:58:41.281Z ring-wrtc [Front Door] Websocket signaling for Ring cloud connected successfully
2023-02-16T13:58:41.711Z ring-wrtc [Front Door] Live stream transcoding process has started
2023-02-16T13:58:41.786Z ring-wrtc [Front Door] Live stream WebRTC session has disconnected
2023-02-16T13:58:41.786Z ring-mqtt [Front Door] ring/ad5195e5-48d9-4198-84d1-6893943d3f1a/camera/9c7613398876/stream/state OFF
2023-02-16T13:58:41.787Z ring-attr [Front Door] ring/ad5195e5-48d9-4198-84d1-6893943d3f1a/camera/9c7613398876/stream/attributes {"status":"inactive"}
2023-02-16T13:58:41.821Z ring-rtsp [Front Door] State indicates live stream has gone inactive
2023-02-16T13:58:41.822Z ring-rtsp [go2rtc] ERR github.com/AlexxIT/go2rtc/cmd/streams/producer.go:52 > error="exec: %!s(<nil>)" url="exec:/app/ring-mqtt/scripts/start-stream.sh 9c7613398876 live ring/ad5195e5-48d9-4198-84d1-6893943d3f1a/camera/9c7613398876 {output}"
2023-02-16T13:58:41.822Z ring-rtsp [go2rtc] DBG [streams] can't stop none producer
2023-02-16T13:58:41.822Z ring-rtsp [go2rtc] WRN [rtsp] error="source 0 error: exec: %!s(<nil>)" stream=9c7613398876_live
```

Any hint would be appreciated.

**Comment by tsightler** [comment] 2023-02-16 14:17
> No livestreams no snapshots.

Snapshots are completely unrelated to livestream, except from the fact that battery cameras can't take snapshots while a stream is in progess, and nothing much has changed about them in the last year.  Please provide full logs.  If you don't want to share them here you can email them to me with same username at gmail.

**Comment by tsightler** [comment] 2023-02-16 15:05
Thanks for providing the logs.  Unfortunately, there's not much to go on.  The key issue here is not the go2rtc error which you referenced, as that is just a symptom.  The actual issue is that the WebRTC session starts, but then fails almost immediately, as can be seen here:

```
2023-02-16T13:58:41.711Z ring-wrtc [Front Door] Live stream transcoding process has started
2023-02-16T13:58:41.786Z ring-wrtc [Front Door] Live stream WebRTC session has disconnected
```

go2rtc is just reporting an error because the WebRTC session failed to start.

Unfortunately, I have no idea why and very little visibility into why as the connection is handled by the underlying werift library.  Are you sure your network can pass UDP packets with no issue?

We can get more insight into what is happening with werift by enabling werift debug output using the DEBUG environment varable.  Please run ring-mqtt with DEBUG set as follows:

`DEBUG=ring-*,werift*`

After doing that, please send logs. which should then include a lot of additional debug data for werift.  Maybe we can figure out why the WebRTC connection is failing.

**Comment by tsightler** [comment] 2023-02-17 18:00
Hi, any update with logs that include werift debug as asked for above?

**Comment by scarolan** [comment] 2023-02-18 02:46
I have the same issue and managed to capture a werift error:

```
2023-02-18T02:45:13.953Z werift-dtls : packages/dtls/record/receive.ts : err  ContentType.alert Alert { level: 2, description: 51 } DecryptError flight 5 lastFlight [
  Finished {
    verifyData: <Buffer a7 c3 29 9d 7d da 55 e8 f1 81 e8 ae>,
    msgType: 20,
    messageSeq: 4
  }
]
2023-02-18T02:45:13.954Z werift-dtls : packages/dtls/src/socket.ts : err  catch udpOnMessage error Error: alert fatal error
    at /app/ring-mqtt/node_modules/werift/lib/dtls/src/record/receive.js:76:23
    at IceTransport.value [as onData] (/app/ring-mqtt/node_modules/werift/lib/dtls/src/socket.js:123:94)
    at Object.execute (/app/ring-mqtt/node_modules/werift/lib/webrtc/src/transport/dtls.js:408:26)
    at Event.execute (/app/ring-mqtt/node_modules/rx.mini/lib/core/index.js:18:30)
    at Connection.dataReceived (/app/ring-mqtt/node_modules/werift/lib/ice/src/ice.js:743:25)
    at StunProtocol.datagramReceived (/app/ring-mqtt/node_modules/werift/lib/ice/src/stun/protocol.js:91:27)
    at transport.onData (/app/ring-mqtt/node_modules/werift/lib/ice/src/stun/protocol.js:78:62)
    at Socket.<anonymous> (/app/ring-mqtt/node_modules/werift/lib/ice/src/transport.js:80:22)
    at Socket.emit (node:events:513:28)
    at UDP.onMessage [as onmessage] (node:dgram:930:8)
2023-02-18T02:45:13.984Z werift-dtls : packages/dtls/record/receive.ts : err  ContentType.alert Alert { level: 2, description: 51 } DecryptError flight 5 lastFlight [
  Finished {
    verifyData: <Buffer e0 75 47 67 c1 8e f6 25 24 e8 30 8c>,
    msgType: 20,
    messageSeq: 4
  }
]
2023-02-18T02:45:13.984Z werift-dtls : packages/dtls/src/socket.ts : err  catch udpOnMessage error Error: alert fatal error
    at /app/ring-mqtt/node_modules/werift/lib/dtls/src/record/receive.js:76:23
    at IceTransport.value [as onData] (/app/ring-mqtt/node_modules/werift/lib/dtls/src/socket.js:123:94)
    at Object.execute (/app/ring-mqtt/node_modules/werift/lib/webrtc/src/transport/dtls.js:408:26)
    at Event.execute (/app/ring-mqtt/node_modules/rx.mini/lib/core/index.js:18:30)
    at Connection.dataReceived (/app/ring-mqtt/node_modules/werift/lib/ice/src/ice.js:743:25)
    at StunProtocol.datagramReceived (/app/ring-mqtt/node_modules/werift/lib/ice/src/stun/protocol.js:91:27)
    at transport.onData (/app/ring-mqtt/node_modules/werift/lib/ice/src/stun/protocol.js:78:62)
    at Socket.<anonymous> (/app/ring-mqtt/node_modules/werift/lib/ice/src/transport.js:80:22)
    at Socket.emit (node:events:513:28)
    at UDP.onMessage [as onmessage] (node:dgram:930:8)
```

**Comment by tsightler** [comment] 2023-02-18 19:07
@scarolan Could you please send the full log to my email address?  I don't think just the error will be enough to track this down as we need to see negotiated algorithms, etc.  My email is the same username at gmail.  Thanks!

**Comment by tsightler** [comment] 2023-02-19 14:41
I've switched this from support to bug because I believe this is a bug in the upstream werift code, however, without full debug output I won't be able to submit anything upstream or even attempt to debug it myself since I am not able to reproduce the issue.

If someone else is experiencing this issue, please enabled werift debugging as described above and send the output to me either here, or via email (same username at gmail).  If you are willing to provide me temporary access to the camera, to see if I can reproduce the issue, that would be even better.

**Comment by scarolan** [comment] 2023-02-26 20:17
> @scarolan Could you please send the full log to my email address? I don't think just the error will be enough to track this down as we need to see negotiated algorithms, etc. My email is the same username at gmail. Thanks!

Sure thing, as soon as I get moved and new HA setup I'll try to replicate this again and provide a full log dump.

**Comment by juvenalandres** [comment] 2023-02-26 20:25
> @scarolan Could you please send the full log to my email address? I don't think just the error will be enough to track this down as we need to see negotiated algorithms, etc. My email is the same username at gmail. Thanks!

I've sent you the logs with werift debug. Hope it helps.

Cheers

**Comment by tsightler** [comment] 2023-03-15 17:01
Could any of you that are experiencing issues please try with the latest 5.2.0 version?  At first glance from the logs I have received it seems both cases had fairly complex host network setups with lots of candidates.  There are some improvements in the upstream werift code around stun candidate negotiation that may have helped.

Otherwise, I'm going to need more logs with werift debug enabled.

**Comment by mikegodin23** [comment] 2023-03-20 13:23
Hi.
I have the Ring Doorbell Wired in HA using Zigbee2mqtt and everytime I switch on the Live stream on Controls (inside the Mosquitto broker integration) it instantly turns off again.
Can anyone help?
Thanks.
Miguel

**Comment by tsightler** [comment] 2023-03-24 21:16
Closing this since I'm not really getting any responses.  If someone experiences this and wants to actively work on it, please feel free to re-open.

**Closed as completed by tsightler** 2023-03-24 21:16 UTC
Labels: bug
