### ISSUE TITLE
[FR] - Manually Request Snapshot

### ISSUE THREAD

**Issue by seanmccabe** [tsightler/ring-mqtt#148] opened 2021-03-08 03:45 UTC
Wondering if it is possible to manually request a snapshot via MQTT?

Can see that the snapshot frequency can be reduced to 1 second. So a hacky way would be to reduce the frequency of the snapshots down to one second, or maybe a little more, then back up.
Ideally trying to have it so if someone rings the bell (I have external push button bell to the Ring video doorbell then it will trigger a snapshot.
This I can then send through a HA notification

**Comment by tsightler** [comment] 2021-03-08 04:10
You can set it to 1 second, but it should override this to 10 seconds as the minimum and the underlying ring-client-api also caches the image for at least 10 seconds as well, so any snapshot request would just return the cached image anyway.  We have to set some lower limit on this to avoid abuse of the Ring API which is just not designed for a high snapshot frequency (I even worry about 10 seconds as the Ring app doesn't do anything more often than 30 seconds).

That's the same reason I don't have an on demand capability either, although I guess since the underlying API is limited maybe it would be OK, but I really don't want to get into this because then people will try to abuse it and then be opening issues wanting to know what it doesn't refresh as often as they want.

I don't understand what you mean by an "external push button bell", does it cause a ding event to be triggered?  If so, I would consider implementing grabbing a snapshot on ding and not just motion events, although normally the motion event should happen before the ding event, unless you have motion turned off completely.

**Comment by seanmccabe** [comment] 2021-03-08 19:23
>I don't understand what you mean by an "external push button bell", does it cause a ding event to be triggered?

Yer sorry that sentence didnt make much sense. I have a push button that is external to the ring doorbell. As the Ring doorbell is behind a security door so you can't actually press the button.
Was hoping to find a way to trigger a Ring ding event without having to push the button on the Ring itself, is that possible?
At the same time it would then take a snapshot sending a notification via HA.

Totally understand regardng the on demand capability. Little frustrating as it would be perfect for my scenario; push button, get snapshot. Would look to limit it in HA anyway, don't need a snapshot if someone double presses the bell.

Obviously if you implement snapshot on ding (which tbh would be ideal too), but then can trigger a ding event some other way other than physically pressing the button, it does the same thing as I am requesting, with the added bonus the Ring camera would flash ring light meaning someone would know they've pressed the button.

**Comment by tsightler** [comment] 2021-03-09 01:09
Yeah, I don't think there's any way to force a ding event from the app side.  We're using the same API that the Ring app uses, so if the Ring app doesn't have some way to trigger something like that (why would it), then it's unlikely to be available in ring-client-api either.  I'm sure it would be possible to reverse engineer the API used by the camera itself and then force an event, but that's far beyond the scope of this project.

Out of curiosity, what good is the Ring doorbell without being able to press the doorbell?  I mean, I guess you could still get motion events, but then, if you get motion events, you should already be getting a snapshot.  Without motion events or a doorbell press I'm struggling to see what a Ring doorbell does since I think it would never record anything in this case.

The primary reason I didn't implement snapshot on ding is that my experience says that, in a lot of cases, you end up with a snapshot of a hand obscuring the person.  The snapshot from the motion event, which should happen first, is usually a better view of the person.

I'll consider implementing snapshot on ding if I get enough requests, it's trivially easy to do other than the annoyance of adding even more configurable options, but it doesn't sound like that would do you any good anyway.  I don't currently plan on implementing on-demand request for snapshots, but I won't say never!

**Comment by seanmccabe** [comment] 2021-03-09 01:21
> Out of curiosity, what good is the Ring doorbell without being able to press the doorbell? I mean, I guess you could still get motion events, but then, if you get motion events, you should already be getting a snapshot. Without motion events or a doorbell press I'm struggling to see what a Ring doorbell does since I think it would never record anything in this case.

It does have knock detection, but its very rare that someone will bang on the security door. PI've tested that and it seems to work. Personally do prefer they dont since the baby is in the bedroom next to it. But yer, I am primarily using it as a security camera, plus I have the peep-hole version, so have a manual peep-hole as well. Basically my front door doesn't have glass, and you don't have a view of anyone approaching so its more a security thing, especially when family home without me, and on evenings.

Was just going to be ideal if I could tie more deeply into it and replicate its functionality with the external button.
But you are right, I am getting motion events, so I do get a snapshot from that and that seems to pick-up people fairly well, but ideal if the event could say whether it thinks its a person like the app does. Not sure how well that will work with security door in front though. Be the same with the snapshot, will get a meshed view of the person. So not quite a hand like you get ;)

The official integration in HA also provides a video link (not live), much like the snapshot here. Any plans on integrating that? I'm not fussed by live video, always find by the time it loads its useless, especially for a doorbell, but good for reviewing if it is legitamately a person, or just something else setting off the camera.

**Comment by tsightler** [comment] 2021-03-09 01:43
Person detection is something I'm working on but it's difficult because I can't get any of my cameras to actually give me person detected notifications, even in the Ring app.

I'm not trying to reproduce the native HA capability as, while this project, while it works well with HA, was not built specifically for HA but for generic MQTT.

MQTT isn't really designed for streaming and I'm limited with what I can do with that to the capabilities of the Home Assistant MQTT camera component, which pretty much just takes still images.  I could theoretically do a live stream by converting into MJPEG, but there's no way to trigger this behavior automatically so it would require a lot of manual setup all to get get 1 frame-per-second MJPEG images via MQTT.  Just doesn't seem practical to me when the native component already supports it.

I think I'll close this for now, it doesn't sound like anything I can change will really change your behavior.

**Closed as completed** 2021-03-09 01:44 UTC
Labels: enhancement
