### ISSUE TITLE
Ring Intercom - Some entities are unknown/unavailable

### ISSUE THREAD

**Issue by lesgrebe** [tsightler/ring-mqtt#633] opened 2023-05-17 08:51 UTC
Hello,

for some reason the Battery level, Wireless Signal and Last Update Status not updating anymore on Ring Intercom (I´ve noticed it today). I´ve already deleted all authorized devices from my ring account an forced a reauthentication in HA which ends unfortunately in the same behavior. Ding and Lock Entities are available, all other entities are unavailable or unknown. A restart of HA but also the integration or the addon didn´t resolve this. I´m only using the Ring Interom, no other devices from Ring. I´m located in Austria (Europe).

**Entities / Integration:**
![image](https://github.com/tsightler/ring-mqtt/assets/37287548/130d0d59-af93-476c-9ade-58ea5040610c)
![image](https://github.com/tsightler/ring-mqtt/assets/37287548/50488c00-d4bc-4214-97e6-a853a077fcd7)

**Ring authorized devices:**
![image](https://github.com/tsightler/ring-mqtt/assets/37287548/3aaf1211-ec81-4401-95c6-59daad5fb9b4)

**Logfile informations:**
[03cabcc9_ring_mqtt_2023-05-17T08-31-15.362Z.log](https://github.com/tsightler/ring-mqtt/files/11495824/03cabcc9_ring_mqtt_2023-05-17T08-31-15.362Z.log)

![image](https://github.com/tsightler/ring-mqtt/assets/37287548/14cc5070-a393-45b7-b482-123c2b9ba168)
**Versions (HA, MQTT):**
![image](https://github.com/tsightler/ring-mqtt/assets/37287548/47e71a46-e56f-48c3-b112-cab13c2487f0)
![image](https://github.com/tsightler/ring-mqtt/assets/37287548/50e59944-9113-45d1-a7a7-e285ba3e9a45)

Maybe there there is an issue in the Ring API or on my end but it worked for about 3-4 months without any problems.
_**Thanks for your help!!!**_

Regards
Michi

**Comment by tsightler** [comment] 2023-05-17 15:27
Duplicate of https://github.com/tsightler/ring-mqtt/issues/632

**Closed as completed by tsightler** 2023-05-17 15:27 UTC
Labels: support

**Comment by spanzetta** [comment] 2023-05-18 05:08
Now it works again..
