### ISSUE TITLE
Auth failure after update to 3.1.1

### ISSUE THREAD

**Issue by JOHLC** [tsightler/ring-mqtt#83] opened 2020-08-07 02:26 UTC
After updating, my ring auth is no longer working, reset the token and tried to setup again but I am getting this error:

Running ring-mqtt...
2020-08-07T02:24:25.613Z ring-mqtt Using configuration file: /data/options.json
2020-08-07T02:24:25.614Z ring-mqtt Reading latest saved refresh token from file: /data/ring-state.json
2020-08-07T02:24:25.614Z ring-mqtt No newer refresh token found, will use token from config file.
2020-08-07T02:24:25.620Z ring-mqtt No refresh token found, go to http://<ip_address>:55123/ to generate a valid token.
(node:6) UnhandledPromiseRejectionWarning: Error: Failed to fetch oauth token from Ring. Verify that your email and password are correct. (error: access_denied)
    at RingRestClient.<anonymous> (/ring-mqtt/node_modules/ring-client-api/lib/api/rest-client.js:166:23)
    at Generator.throw (<anonymous>)
    at rejected (/ring-mqtt/node_modules/ring-client-api/lib/api/rest-client.js:25:65)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:6) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:6) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by tsightler** [comment] 2020-08-07 02:47
The error seems to indicate that you entered an invalid username and password (access denied from the authentication attempt).  Are you sure you used a valid account?  You can always just restart the addon and try again.

**Comment by JOHLC** [comment] 2020-08-07 02:48
I am able to login via the website with the same account / creds. 
Copy paste.

Oddly enough I am successful with the addon by using my personal, instead of the shared account I created for Home Assistant. Same password even.

**Comment by JOHLC** [comment] 2020-08-07 02:49
Weird right?

**Comment by JOHLC** [comment] 2020-08-07 02:54
Also where is your Buy me a coffee link? I use this addon every single day and cannot thank you enough.

**Comment by tsightler** [comment] 2020-08-07 02:57
Even more weird as there were absolutely zero chanhes to the code that gets the token so if it worked before and not now I have no idea why.  Also the error is super clear, access denied is pretty basic auth failure, so I can't see how it could be anything else.  Really weird.

Also, I use a shared account with no issues.  Perhaps you could try an alternative method to get a token, the web page is just a poorlt implement hack so maybe it's something there, although I don't know what.

**Comment by toscano** [comment] 2020-08-07 14:33
A common issue is the encoding of special characters during the POST. Try a
password that doesn't have an ampersand and one that does to rule this out.

**Comment by JOHLC** [comment] 2020-08-07 14:37
Hello,
Thanks for the heads up.
My password doesn't contain an &

It does contain special characters however, using the same password with another account works
I'm going to do some more testing tonight.

Thanks.

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by tsightler** [comment] 2020-08-07 15:02
I thought about the password encoding as well, because I'm definitely doing nothing special there, but the fact that it works with another account using the same password made me think that wasn't it.  I also have some pretty weird characters in my service account password with no issues.

The web based tool is just a very quickly implemented wrapper around the existing functions in ring-client-api and I did update to the latest API version in the most recent push, perhaps something changed there, although it seems to work for me.  You can always generate the token from the cli of any machine with node installed by doing something like:

$ npx -p ring-client-api ring-auth-cli

Or, from HASS.io you can get CLI access and run ring-auth-cli from within the addon container.

**Comment by tsightler** [comment] 2020-08-07 16:08
I've tested everything I can think of with this and all auth works just fine got me.  I get a successful token each and every time, no issues.  I tried with existing shared accounts, main accounts, new accounts, I tried huge, complex passwords.  I'm not sure what else could be the issue here.

**Comment by tsightler** [comment] 2020-08-11 18:03
I have pushed version 3.2.1 which includes some enhacements to the Web UI including checking for valid user/password and token entry.  Also, it's no longer required to manually copy and paste the token as the token is automatically saved into the new ring-state.json file.

I've tested authentication with this quite completely, using 3 different accounts with all types of generated passwords.  The only authentication failures I could reproduce were when I had requested too many 2FA tokens too quickly and Ring blocked the account for about 12 hours (interestingly, the error message indicated it would only be blocked for 10 minutes).

If you are still having issues please let me know and we can troubleshoot.  Otherwise I will close this issue in a few days.

**Comment by JOHLC** [comment] 2020-08-16 04:32
I finally got to circle back to this.
Right now I am signed in as my personal account and it works. 
I'm trying to change the login, but it keeps grabbing my current refresh token for my personal account.
I tried removing the key from config.

How can I get the add-on to host the web UI again?

**Comment by JOHLC** [comment] 2020-08-16 04:37
I uninstalled then reinstalled, added my second account and auth works now. 
Closing

**Comment by JOHLC** [comment] 2020-08-16 04:38
Is this you? https://www.paypal.com/paypalme/tsightler/

**Closed as completed** 2020-08-16 04:37 UTC

**Comment by tsightler** [comment] 2020-08-16 17:44
Thanks for the feedback and glad to know you got it working.  In a future version of the add-on the web UI will simply run all the time so that you can generate a new token with a new account even if it is already running.  It will also automatically detect MQTT connection info using the HA API.  For now, if the current token is functional the only way to use a new account is to do what you did, uninstall/reinstall, unless you manually connect to the container and delete the existing token.  Hopefully when I release 4.0 in a few weeks the entire auth will be handled via the UI and require no config at all (other than token generation) to get it working, at least, that's the plan.

No that isn't me!  :)
While I appreciate the gesture I don't really need any donations for this project.  I'm fortunate to have a great job that pays the bills quite nicely and I started this project mainly as an excuse to learn Javascript (something I'm still not good at but at least I've learned enough to be dangerous) and it was useful for my own home automation.

If you have money to donate I'd suggest picking a charity you can be passionate about or perhaps even select some person you know that is in need (I know plenty in that state during these times) and send them the money instead.  Most likely that's what I would do with it anyway.
