### ISSUE TITLE
Docker output stopped

### ISSUE THREAD

**Issue by martynwendon** [tsightler/ring-mqtt#150] opened 2021-03-16 11:30 UTC
So I installed ring-mqtt a few weeks ago in Docker and it seemed to be running OK.

I just came back to it today to start integrating it into my Node Red setup.

Unfortunately it seems to have stopped about 6 days ago, no error that I can see ..... just no more logging.

As far as I can tell it's still running, but I can see it's no longer connected to the MQTT broker (not listed in the current client list).

Rather than just restart the container, I thought I'd see if there was anything you wanted me to pull from the current instance to see what might have happened?

![image](https://user-images.githubusercontent.com/1092273/111301498-3502a600-864a-11eb-8b82-0a92ae4ae248.png)

![image](https://user-images.githubusercontent.com/1092273/111301581-4b106680-864a-11eb-9528-d1e01950277e.png)

**Comment by tsightler** [comment] 2021-03-16 19:44
By chance do you have only cameras, or do you also have an alarm and/or smart lighting hub?

**Comment by martynwendon** [comment] 2021-03-16 19:47
I've got a Video Doorbell 2, a couple of Stick Up Cams and three Indoor Cams.

**Comment by tsightler** [comment] 2021-03-16 20:03
Yep, so no alarm/smart lighting hub which means no websocket to monitor, which would have provided more detail.

Ring's camera API is pretty old school, it literally relies on polling to determine if there are new events or not and, because this is handled by the underlying ring-client-api, that connectivity status is mostly invisible.  With the alarm/smart lighting, there's a great websocket to monitor so you know if it goes down and reconnects start, but with cameras only, there's not much to go on.

What the script currently does is every camera calls getHealth() in a loop every 60 seconds and, if that doesn't return it assumes the camera is offline.  You can see above that it tagged the cameras offline which means that ring-client-api was not returning on getHealth() call.   Unfortunately I don't know if there's much else that can be gleaned from this.  My guess is that, for whatever reason, ring-client-api was unable to re-establish the connection with the Ring servers so getHealth() continued to fail and thus the cameras never came back online.

The script is likely not well tested with the camera only use case.  Without the websocket it is certainly less robust against minor Ring or network outages.  The getHealth() calls are the only way I've figured out to even know if the API is responding or not but it's supposed to automatically reconnect when possible.  If it continues to happen you can enable debugging for the ring-client-api module and, although it is very wordy, that's the only likely place that would tell us anything.

**Comment by tsightler** [comment] 2021-03-16 20:41
I'm going to close this for now.  If you continue to have issues feel free to collect logs with debug from ring-client-api enabled and we can look into it deeper.

**Closed as completed by tsightler** 2021-03-16 20:41 UTC

**Comment by martynwendon** [comment] 2021-03-16 23:03
> free to collect logs with debug from ring-client-api enabled 

How can I do this?

I tried setting DEBUG env variable to various combinations of "ring-mqtt ring-client-api ring" but that didn't seem to produce anything more than just ring-mqtt logs.  If I set DEBUG to "*" I got lots more output but it mostly seems to be mqtt related (certainly nothing stands out as being prefixed with "ring", "ring-client" or similar.

**Comment by tsightler** [comment] 2021-03-17 02:50
I don't know how much debugging ring-client-api has at this point.  There's at least a little available with DEBUG=ring and then some of the low layer socket stuff can be seen with DEBUG=socket*.  I'm not really sure if there's anything for the rest/http stuff the polling interface as I haven't needed to go that deep into that project.

**Comment by martynwendon** [comment] 2021-03-17 09:21
Thanks for the pointers, will see how it goes over the next few weeks and if anything more informative appears in the logging.

**Comment by tsightler** [comment] 2021-03-19 16:31
Is there any chance that you had an internet outage for a few minutes that might have triggered this?  I've been attempting to reproduce and I think I might have been able to create a case where it fails.  The script itself doesn't appear to be hung, but after an internet outage there's no more polling events coming from the API and I'm not sure why, however, I think I'm going to implement the connection monitor in a completely different way and see if that fixes it.

**Comment by martynwendon** [comment] 2021-03-19 18:47
I don't believe so, at least my router doesn't have any disconnect event that coincides with that timing. But it's always possible there could have been something further upstream perhaps.

Happy to test anything you need testing, this is a parallel install to another Ring implementation at the moment so not in full use yet.

**Comment by tsightler** [comment] 2021-03-23 01:28
Just FYI, I've been doing some testing around this as I had one other report of similar behavior and, based on my testing, it appears to be a bug in the latest node v12, not in the ring-mqtt code itself.  I can reproduce the issue fairly frequently when running v12 by block the network connection to the Ring servers for a few minutes at a time.  However, with node v14 (which is the current LTS version) I cannot reproduce this behavior at all, even if I keep the connection blocked for hours, as soon as I return the connection, it reconnects just fine generally in about a minute or so.

I guess I'll have to figure out how to address this in the next release.  The docker image is based on the homeassistant addon base image which is in turn based on Alpine 3.12, which only has nodejs 12 in the repo.

**Comment by martynwendon** [comment] 2021-03-23 08:49
Thanks for the update, at least you've made progress in identifying a potential cause!

For the record I've so far not had the problem again, but am keeping a close eye on things as I've now integrated ring2mqtt to my live system so any issues will be spotted pretty quickly.

**Comment by martynwendon** [comment] 2021-04-15 08:09
Thought I'd post an update, it's been solid since I last restarted but failed again yesterday.

Nothing particularly interesting in the logs as far as I can see.


```
2021-04-14T09:06:03.033Z ring-mqtt File /data/ring-state.json saved with updated refresh token.

2021-04-14T09:07:53.482Z ring-mqtt ring/gcr3m5-2qvqr-0/camera/343ea46ccb7a/info/state {"batteryLevel":"100","firmwareStatus":"Up to Date","lastUpdate":"2021-04-14T05:00:37+00:00","wirelessNetwork":"AHSWIFII","wirelessSignal":-58}

2021-04-14T09:07:53.483Z ring-mqtt ring/gcr3m5-2qvqr-0/camera/54e019044a42/info/state {"batteryLevel":"76","firmwareStatus":"Up to Date","lastUpdate":"2021-04-14T01:04:49+00:00","wirelessNetwork":"AHSWIFIB","wirelessSignal":-63}

2021-04-14T09:07:53.486Z ring-mqtt ring/gcr3m5-2qvqr-0/camera/3415133ccd2f/info/state {"batteryLevel":"100","firmwareStatus":"Up to Date","lastUpdate":"2021-04-14T07:34:24+00:00","wirelessNetwork":"AHSWIFIB","wirelessSignal":-56}

2021-04-14T09:09:53.468Z ring-mqtt ring/gcr3m5-2qvqr-0/camera/54e019373ce0/info/state {"firmwareStatus":"Up to Date","lastUpdate":"2021-04-14T08:03:10+00:00","wirelessNetwork":"AHSWIFIB","wirelessSignal":-30}

2021-04-14T09:12:53.496Z ring-mqtt ring/gcr3m5-2qvqr-0/camera/343ea46ccb7a/info/state {"batteryLevel":"100","firmwareStatus":"Up to Date","lastUpdate":"2021-04-14T05:00:37+00:00","wirelessNetwork":"AHSWIFII","wirelessSignal":-58}

2021-04-14T09:12:53.498Z ring-mqtt ring/gcr3m5-2qvqr-0/camera/54e019044a42/info/state {"batteryLevel":"76","firmwareStatus":"Up to Date","lastUpdate":"2021-04-14T01:04:49+00:00","wirelessNetwork":"AHSWIFIB","wirelessSignal":-63}

2021-04-14T09:12:53.499Z ring-mqtt ring/gcr3m5-2qvqr-0/camera/3415133ccd2f/info/state {"batteryLevel":"100","firmwareStatus":"Up to Date","lastUpdate":"2021-04-14T07:34:24+00:00","wirelessNetwork":"AHSWIFIB","wirelessSignal":-56}

2021-04-14T09:14:53.474Z ring-mqtt ring/gcr3m5-2qvqr-0/camera/54e019373ce0/info/state {"firmwareStatus":"Up to Date","lastUpdate":"2021-04-14T08:03:10+00:00","wirelessNetwork":"AHSWIFIB","wirelessSignal":-30}

2021-04-14T09:17:53.468Z ring-mqtt ring/gcr3m5-2qvqr-0/camera/54e019044a42/info/state {"batteryLevel":"76","firmwareStatus":"Up to Date","lastUpdate":"2021-04-14T01:04:49+00:00","wirelessNetwork":"AHSWIFIB","wirelessSignal":-63}

2021-04-14T09:17:53.469Z ring-mqtt ring/gcr3m5-2qvqr-0/camera/3415133ccd2f/info/state {"batteryLevel":"100","firmwareStatus":"Up to Date","lastUpdate":"2021-04-14T07:34:24+00:00","wirelessNetwork":"AHSWIFIB","wirelessSignal":-56}

2021-04-14T09:17:53.478Z ring-mqtt ring/gcr3m5-2qvqr-0/camera/343ea46ccb7a/info/state {"batteryLevel":"100","firmwareStatus":"Up to Date","lastUpdate":"2021-04-14T05:00:37+00:00","wirelessNetwork":"AHSWIFII","wirelessSignal":-58}

2021-04-14T09:19:53.499Z ring-mqtt ring/gcr3m5-2qvqr-0/camera/54e019373ce0/info/state {"firmwareStatus":"Up to Date","lastUpdate":"2021-04-14T08:03:10+00:00","wirelessNetwork":"AHSWIFIB","wirelessSignal":-30}

2021-04-14T09:22:53.506Z ring-mqtt ring/gcr3m5-2qvqr-0/camera/343ea46ccb7a/info/state {"batteryLevel":"100","firmwareStatus":"Up to Date","lastUpdate":"2021-04-14T05:00:37+00:00","wirelessNetwork":"AHSWIFII","wirelessSignal":-58}

2021-04-14T09:22:53.507Z ring-mqtt ring/gcr3m5-2qvqr-0/camera/3415133ccd2f/info/state {"batteryLevel":"100","firmwareStatus":"Up to Date","lastUpdate":"2021-04-14T07:34:24+00:00","wirelessNetwork":"AHSWIFIB","wirelessSignal":-56}

2021-04-14T09:22:53.508Z ring-mqtt ring/gcr3m5-2qvqr-0/camera/54e019044a42/info/state {"batteryLevel":"76","firmwareStatus":"Up to Date","lastUpdate":"2021-04-14T01:04:49+00:00","wirelessNetwork":"AHSWIFIB","wirelessSignal":-63}

2021-04-14T09:24:53.500Z ring-mqtt ring/gcr3m5-2qvqr-0/camera/54e019373ce0/info/state {"firmwareStatus":"Up to Date","lastUpdate":"2021-04-14T08:03:10+00:00","wirelessNetwork":"AHSWIFIB","wirelessSignal":-30}

2021-04-14T09:27:53.491Z ring-mqtt ring/gcr3m5-2qvqr-0/camera/3415133ccd2f/info/state {"batteryLevel":"100","firmwareStatus":"Up to Date","lastUpdate":"2021-04-14T07:34:24+00:00","wirelessNetwork":"AHSWIFIB","wirelessSignal":-56}

2021-04-14T09:27:53.500Z ring-mqtt ring/gcr3m5-2qvqr-0/camera/343ea46ccb7a/info/state {"batteryLevel":"100","firmwareStatus":"Up to Date","lastUpdate":"2021-04-14T05:00:37+00:00","wirelessNetwork":"AHSWIFII","wirelessSignal":-58}

2021-04-14T09:27:53.517Z ring-mqtt ring/gcr3m5-2qvqr-0/camera/54e019044a42/info/state {"batteryLevel":"76","firmwareStatus":"Up to Date","lastUpdate":"2021-04-14T01:04:49+00:00","wirelessNetwork":"AHSWIFIB","wirelessSignal":-63}

2021-04-14T09:29:53.514Z ring-mqtt ring/gcr3m5-2qvqr-0/camera/54e019373ce0/info/state {"firmwareStatus":"Up to Date","lastUpdate":"2021-04-14T08:03:10+00:00","wirelessNetwork":"AHSWIFIB","wirelessSignal":-30}

2021-04-14T09:32:53.508Z ring-mqtt ring/gcr3m5-2qvqr-0/camera/343ea46ccb7a/info/state {"batteryLevel":"100","firmwareStatus":"Up to Date","lastUpdate":"2021-04-14T05:00:37+00:00","wirelessNetwork":"AHSWIFII","wirelessSignal":-58}

2021-04-14T09:32:53.509Z ring-mqtt ring/gcr3m5-2qvqr-0/camera/54e019044a42/info/state {"batteryLevel":"76","firmwareStatus":"Up to Date","lastUpdate":"2021-04-14T01:04:49+00:00","wirelessNetwork":"AHSWIFIB","wirelessSignal":-63}

2021-04-14T09:32:53.516Z ring-mqtt ring/gcr3m5-2qvqr-0/camera/3415133ccd2f/info/state {"batteryLevel":"100","firmwareStatus":"Up to Date","lastUpdate":"2021-04-14T07:34:24+00:00","wirelessNetwork":"AHSWIFIB","wirelessSignal":-56}

2021-04-14T09:34:53.512Z ring-mqtt ring/gcr3m5-2qvqr-0/camera/54e019373ce0/info/state {"firmwareStatus":"Up to Date","lastUpdate":"2021-04-14T08:03:10+00:00","wirelessNetwork":"AHSWIFIB","wirelessSignal":-30}

2021-04-14T09:37:53.213Z ring-mqtt ring/gcr3m5-2qvqr-0/camera/3415133ccd2f/info/state {"batteryLevel":"100","firmwareStatus":"Up to Date","lastUpdate":"2021-04-14T07:34:24+00:00","wirelessNetwork":"AHSWIFIB","wirelessSignal":-56}

2021-04-14T09:37:53.223Z ring-mqtt ring/gcr3m5-2qvqr-0/camera/54e019044a42/info/state {"batteryLevel":"76","firmwareStatus":"Up to Date","lastUpdate":"2021-04-14T01:04:49+00:00","wirelessNetwork":"AHSWIFIB","wirelessSignal":-63}

2021-04-14T09:37:53.224Z ring-mqtt ring/gcr3m5-2qvqr-0/camera/343ea46ccb7a/info/state {"batteryLevel":"100","firmwareStatus":"Up to Date","lastUpdate":"2021-04-14T05:00:37+00:00","wirelessNetwork":"AHSWIFII","wirelessSignal":-58}

2021-04-14T09:39:53.529Z ring-mqtt ring/gcr3m5-2qvqr-0/camera/54e019373ce0/info/state {"firmwareStatus":"Up to Date","lastUpdate":"2021-04-14T08:03:10+00:00","wirelessNetwork":"AHSWIFIB","wirelessSignal":-30}

2021-04-14T09:41:53.106Z ring-mqtt ring/gcr3m5-2qvqr-0/camera/3415133ccd2f/status offline

2021-04-14T09:41:53.110Z ring-mqtt ring/gcr3m5-2qvqr-0/camera/54e019044a42/status offline

2021-04-14T09:41:53.114Z ring-mqtt ring/gcr3m5-2qvqr-0/camera/343ea46ccb7a/status offline

2021-04-14T09:41:53.117Z ring-mqtt ring/gcr3m5-2qvqr-0/camera/54e019373ce0/status offline
```

Interestingly at around that time yesterday there were some upstream routing issues with my ISP and certain web sites were unreachable for 30 minutes or so .... twitter, facebook, AWS were some that I noticed. I couldn't say for sure if Ring was impacted but it does seem to match the timeline.

**Comment by tsightler** [comment] 2021-04-15 12:24
Unfortunately, while upgrading node to v14 seemed to address the issues with the alarm going offline due to failure of the websocket to reconnect, there is definitely still an issue with cameras not recovering after a network loss.  Any interruption longer than a few minutes seems to cause an unhandled promise rejection somewhere underneath which leads to loss of polling events.  Unfortunately, this doesn't appear to be an issue with ring-mqtt itself as the trace is lower in the stack.

It's possible I need to take some action once the environment recovers, but, at this point, I haven't been able to find a suitable workaround that allows recovery from this case, other than effectively killing the Ring client and starting over, something that should not be required and that would need some rewriting in order to do correctly.

**Comment by tsightler** [comment] 2021-04-23 19:28
I've pushed 4.5.3 which includes an attempt to workaround the cameras failing to respond to polling after a network outage.  I've tested it extensively and, so far, with this workaround, recovery happens in <60 seconds once the network connection is restored, but there could still be failure cases.  I've opened a few issues with some of the projects that this code is dependent on and hopefully we'll eventually find all of the issues and corner cases.  It seems like this issue was introduced when ring-client-api switch from HTTP1.1 with keepalive to HTTP2, but we can't just revert back because Ring is requiring at least some request to use HTTP2 or it's throttling them.  Unfortunately HTTP2 is still not to the stability of HTTP1.1 in the underlying NodeJS codebase or the libraries using that code, but it seems to be improving pretty quickly so I suspect, over time, the stability will continue to improve.  For now, the workaround I've implemented has worked for me in all cases, but I've only tested interrupting the network connection for up to 1 hour.

**Comment by martynwendon** [comment] 2021-05-06 08:13
Hey there,

Apologies for the delayed reply, I was waiting for the existing docker install to fail again. It was just over 3 weeks again but interestingly there didn't seem to be any internet issues that I could detect this time.

I've updated my Docker build today to the latest 4.5.5 build so I'll let you know how it goes. 

Thanks for your work on this!

**Comment by tsightler** [comment] 2021-05-07 01:58
It's not always internet issues, it can also be issues with Ring servers.  The Ring servers had some pretty weird issues on May 5th (they show only a partial outage on their status page but it seemed slightly worse to me).  In my environment both of my dev systems and my production instance survived these events and recovered.

I'm pretty sure the updates in 4.5.3 and later have this working, but even if they don't I'm not sure what more I can do on the frontend as the reconnects are supposed to be automatically handled by the backend.  I think as HTTP2 support in Node continues to stabilize this probably will likely just slowly go away but I've tested the latest iteration quite a bit and I couldn't break it, while I could break prior versions within 15-30 minutes in most cases so I'm hopeful it will at least be far less likely to occur.

**Comment by tsightler** [comment] 2021-05-10 17:53
More testing has turned up various scenarios which will still cause cameras to stop responding.  For example, if the Ring server your instance is connected to stops responding, it will just wait forever because there's no timeout on the HTTP2 connection. 
 Unfortunately, these issues are all below the ring-mqtt code, I've opened some issues with the respective projects but it will likely be a while before they are resolved.

I could probably work around the issue by detecting the failure and manually disconnecting the API session and starting a new one from scratch but the current code was never written with this in mind and would require some significant refactor for this to work so it's probably not going to be happening any time soon as I don't have the time available for this right now.
