### ISSUE TITLE
Doorbell stopped reporting motion/snapshots

### ISSUE THREAD

**Issue by iceman23e** [tsightler/ring-mqtt#178] opened 2021-06-02 01:38 UTC
Been running the script via the HA addon for a long time without problems with my battery doorbell 2, but randomly now this is the second time my it's stopped reporting motion/snapshots. Everything else reports, like battery, RSSI, etc. I've tried restarting both HA and the addon to no avail. I don't know if it's a Ring problem, but here is the only thing I've seen in the logs:

```
2021-06-02T01:10:47.594Z ring-mqtt Somehow received message to unknown state topic for camera xxx
(node:1) UnhandledPromiseRejectionWarning: HTTPError: Response code 504 (Gateway Timeout)
    at Request.<anonymous> (/app/ring-mqtt-dev/node_modules/got/dist/source/as-promise/index.js:117:42)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Any ideas?

**Comment by tsightler** [comment] 2021-06-02 02:14
Unfortunately this seems to have been caused by relatively recent changes to Ring servers and subsequent changes to ring-client-api to use HTTP2 for connections to the Ring server infrastructure.  I've tried to work around it as best I can, but until ring-client-api (and really, it's underlying dependency of got) manage to stabilize HTTP2 support, I'm not sure if I can do anything about it and I haven't had time to really dig into it.  The core issue is that the connection does not automatically recover in some instances after things like internet outages or Ring service outages (for example, above you clearly had a gateway timeout, but the core issue is the lack of automatic recovery).

You can see here that I have reported it to the ring-client-api author and others are also seeing this behavior in the upstream ring-homebrdige addon project as well so it's not anything specific to this project:

https://github.com/dgreif/ring/issues/616
https://github.com/dgreif/ring/issues/656

I've thought about implementing a workaround where I simply disconnect and reconnect when I detect that there's no longer updates coming from cameras, but, since historically the underlying API just automatically handled all of this, the existing connection framework was never really designed with this in mind and I just haven't had time to work on this project to attempt to refactor it in a way that this would work.

You could probably do something in Home Assistant as I'm assuming the devices do show that they are going offline?  Or do they?  If they show as offline then you could have an automation that restarts the addon as a hackish workaround.

**Comment by iceman23e** [comment] 2021-06-03 03:06
Thanks for your response. Actually, the device still shows online. Everything else updates except for motion status and the snapshot (haven't tried the ding yet). I've tried restarting the addon many times, reinstalling the addon, restarting HA and power cycling the doorbell. Through each of those, everything comes back online, MQTT works just fine, but it's just won't send motion/snapshot updates (again, haven't testing the ding yet).

The only time I seem to see the error in my original post is when the addon is restarting.

**Comment by tsightler** [comment] 2021-06-03 03:18
Do you have motion detection or motion alerts disabled for the camera, either in the app or via some modes based setting?

**Comment by tsightler** [comment] 2021-06-03 03:20
Also, it looks like you are running the dev branch (I see /app/ring-mqtt-dev/ in the logs), I wouldn't suggest this for anything more than testing purposes as the dev branch is, well, dev, it breaks a lot.  There could easily be something broken with it right now.

**Comment by iceman23e** [comment] 2021-06-03 03:21
Nope, everything is turned on and I don't use modes. I had not changed anything when this started happening. It has worked for a long time, then just stopped working.

Yeah, I changed it to dev just to see if it would make any difference. I've since change it back.

**Comment by tsightler** [comment] 2021-06-03 03:37
OK, I may have misinterpreted what you said the first time, when you said it randomly stopped I assumed it quit working and then came back after a restart.  If you're getting this error during startup, I honestly have no idea what it could be.  The error is pretty clearly an HTTP error, specifically a timeout, which is network or server related in some way, but I have no idea what as that's well below my code.

The other thing that's weird is that it somehow impacts snapshots and motion events but not anything else.  It would indeed be interesting to know if ding events work because they are both detected via the same polling.  However, snapshots work completely differently and are created on demand by a simple loop in the code.  When you say they don't work, are you seeing any snapshots being sent in the logs?  Are the failures every time snapshots are polled?  I guess full logs are going to be the only thing that might help at all.

**Comment by iceman23e** [comment] 2021-06-04 01:52
Just sat down to send you the log, restarted the addon and everything is back working now (no timeout error). This is the same thing the last time this happened: didn't work for 2-3 days then, just as quick as it stopped working, it started again.

In any event, while everything was not working, I did test the ding and that did not work either. Interestingly, the attributes of both the motion and ding events were updating properly, just not the state.

Snapshots seemed like they were working looking at the logs because it showed ```<binary_image_data>```, but the snapshot camera entity did not show anything and was ```idle```. Looking at MQTT, no image was actually sent and the attribute was ```"timestamp":null```.

For future reference, is there a way to dump the logs or just copy and paste from the logs in the addon?

**Comment by danielsmith89** [comment] 2021-07-12 15:33
I'm having exactly the same issue. It's hacky, but I basically have a HA automation to restart RingMQTT every 6 hours and so far it seems to have kept doorbell dings/motion events slightly more reliable.

**Comment by tsightler** [comment] 2021-07-12 15:57
Yeah, the drop of ding/motion events after any network or service interruption is a known issue which is impacting all consumers of the ring-client-api package.  Unfortunately the maintainer of that package appears to have the same issue I have, i.e. lack of time to dig into this right now.  I spent some time this weekend trying to make some hackish changes in the hope of figuring out a way to at least detect when the issue occurs, but I failed.  That's the current biggest problem, it's not even possible to know when the API stops sending these events.  If I knew for a fact that the events were not being sent I could probably perform some type of disconnect/reconnect to the API on my side, but as of now the events just silently stop and I can't tell the difference between when there really are no events and when ring-client-api is silently dropping them.

I'm convinced the issue is mostly related to the use of http2 which is buggy as heck in node and the version of got and subsequently the version of got that the API is using, but attempting to upgrade or replace that is quite in-depth and probably above my skill level.

**Comment by tsightler** [comment] 2021-07-15 02:57
I have pushed a new update, 4.5.7, which I hope will improve the reliability of camera events (especially motion/dings) after network/service outages.  I've done a ton of testing and even after leaving the system in a state where the network is unreachable for 12 hours, it recovers, so I'm hopeful it will be more robust.  If you are still seeing the error reported in the OP we should probably research it in more detail

**Comment by danielsmith89** [comment] 2021-07-15 09:55
Thanks, I've just installed and we'll see how it goes. I've turned off my "Restart RingMQTT every 6 hours" automation so can give it a real test.

**Comment by lordlala** [comment] 2021-07-15 14:45
So, it was working great right after I installed your update and now today, it's doing this:

`2021-07-15 10:03:56 WARNING (SyncWorker_5) [homeassistant.components.uptimerobot.binary_sensor] Failed to get new state
2021-07-15 10:04:26 WARNING (SyncWorker_4) [homeassistant.components.uptimerobot.binary_sensor] Failed to get new state
2021-07-15 10:24:03 WARNING (SyncWorker_11) [homeassistant.components.ring] Error fetching Ring history data for device 54e019c4bce6: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2021-07-15 10:28:03 WARNING (SyncWorker_9) [homeassistant.components.ring] Error fetching Ring history data for device 54e019c4bce6: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2021-07-15 10:28:28 WARNING (MainThread) [homeassistant.components.ring] Error fetching Ring active dings data: 504 Server Error: Gateway Time-out for url: https://api.ring.com/clients_api/dings/active?api_version=9
2021-07-15 10:31:52 WARNING (MainThread) [homeassistant.components.ring] Error fetching Ring active dings data: 504 Server Error: Gateway Time-out for url: https://api.ring.com/clients_api/dings/active?api_version=9`

**Comment by danielsmith89** [comment] 2021-07-15 14:49
> So, it was working great right after I installed your update and now today, it's doing this:
> 
> `2021-07-15 10:03:56 WARNING (SyncWorker_5) [homeassistant.components.uptimerobot.binary_sensor] Failed to get new state 2021-07-15 10:04:26 WARNING (SyncWorker_4) [homeassistant.components.uptimerobot.binary_sensor] Failed to get new state 2021-07-15 10:24:03 WARNING (SyncWorker_11) [homeassistant.components.ring] Error fetching Ring history data for device 54e019c4bce6: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')) 2021-07-15 10:28:03 WARNING (SyncWorker_9) [homeassistant.components.ring] Error fetching Ring history data for device 54e019c4bce6: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')) 2021-07-15 10:28:28 WARNING (MainThread) [homeassistant.components.ring] Error fetching Ring active dings data: 504 Server Error: Gateway Time-out for url: https://api.ring.com/clients_api/dings/active?api_version=9 2021-07-15 10:31:52 WARNING (MainThread) [homeassistant.components.ring] Error fetching Ring active dings data: 504 Server Error: Gateway Time-out for url: https://api.ring.com/clients_api/dings/active?api_version=9`

That doesn't look like the RingMQTT add-on to me, that looks like the inbuilt Ring integration in Home Assistant producing those errors. I get them all day long, which is why I switched to RingMQTT

**Comment by lordlala** [comment] 2021-07-15 14:52
Oh... this is going to be a duh moment for me but... you're saying you only
use the Add-on that is in Supervisor and not the Ring integration you find
inside Configuration > Integrations?? And not both?? (serious)

--
Jason Adams

**Comment by danielsmith89** [comment] 2021-07-15 14:55
I only use the built-in one for camera feeds, for everything else I use the RingMQTT addon.

**Comment by tsightler** [comment] 2021-07-15 15:14
As far as I can tell the official Ring integration in HA still uses HTTP 1.1, which causes their requests to the API to be throttled and, if there are enough of them, kicked out.  The ring-client-api project, which ring-mqtt leverages for communicating with Ring's server infrastructure, switched to using HTTP2 quite some months ago to work around these issues.

Previously, when ring-client-api was using HTTP/1.1, it relied 100% on requests to timeout to know whether to retry a request or not.  The HTTP/1.1 implementation has been around a long time and was quite stable so this worked well, however, by comparison, HTTP/2 is quite new and, due to bugs in the HTTP/2 implementation in NodeJS, there are cases where a request effectively hangs forever and never times out, effectively blocking any new requests and thus stopping all future polling.

All I've done is temporarily create a custom fork of ring-client-api where I've implemented a simple timeout so that any request that hasn't received a response in 20 seconds will timeout it's response.  This unblocks future requests so that the pipelines doing polling for updates don't also hang forever.  For me, this seems to have fixed the issue well enough that I can't break it with any of my test scenarios, but I can't simulate all failure modes (I can't easily simulate, for example, various Ring service issues, only network issues).

**Comment by lordlala** [comment] 2021-07-15 15:16
How might one acquire this said fork of yours?

--
Jason Adams

**Comment by tsightler** [comment] 2021-07-15 15:18
You don't need to do anything, if you use the latest ring-mqtt or the ring-mqtt addon, then this fork is included, but it will have no impact on the native Ring integraiton.

**Comment by danielsmith89** [comment] 2021-07-23 14:46
So far, so good. No dropouts for several days - thanks 👍

**Comment by tsightler** [comment] 2021-08-17 04:25
I believe this issue has been addressed with recent changes in ring-client-api so have reverted to upstream with the release of 4.7.0. 
 Closing this for now.

**Closed as completed by tsightler** 2021-08-17 04:25 UTC
Labels: bug
