### ISSUE TITLE
Not connecting to MQTT broker

### ISSUE THREAD

**Issue by chansters** [tsightler/ring-mqtt#103] opened 2020-09-05 21:52 UTC
I upgraded to 4.0.0 and it's now longer communicating with my MQTT broker.  It's able to detect the MQTT broker correctly (127.0.0.1:1883) but I'm getting these messages in the log : 

`2020-09-05T21:50:29.279Z ring-mqtt Attempting to reconnect to MQTT broker...
2020-09-05T21:50:29.281Z ring-mqtt Unable to connect to MQTT broker. connect ECONNREFUSED 127.0.0.1:1883`

I've completed the Ring 2FA authentication and my config file looks like this : 

`enable_cameras: true
enable_modes: false
enable_panic: false
ring_token: ''
location_ids:
  - ''`

**Comment by tsightler** [comment] 2020-09-05 22:33
Are you using the Mosquitto addon or some external broker?  Is your MQTT configured via the UI or configuration.yaml?

**Comment by maddeuce** [comment] 2020-09-05 23:44
same here the addon been running without any issue before this update.  Now it doesn't even start.  It give an oop out msg of "Failed to start addon
Unkown error, see logs"
However there nothing on the log, i mean nothing completely empty weird.

**Comment by chansters** [comment] 2020-09-06 00:06
> Are you using the Mosquitto addon or some external broker? Is your MQTT configured via the UI or configuration.yaml?

I am using the "stock standard" MQTT ... sorry I cannot be more specific. I don't think I installed any external broker.  It's been working great until this latest update.  I installed MQTT when I first installed HA more than a year ago. 

This is what I have in my configuration.yaml : 

`mqtt:
  broker: 10.0.1.7
  discovery: true
  discovery_prefix: homeassistant
  birth_message:
    topic: 'hass/status'
    payload: 'online'
    qos: 0
    retain: false`

I also see MQTT in the UI under "Integration".   And the option "Enable newly added entities" is turned on.

**Comment by tsightler** [comment] 2020-09-06 00:15
I'm not sure what "stock standard" MQTT means.  As far as I know Home Assistant doesn't have an integrated MQTT broker, you have to install one.  These days they recommend installing the Moquitto broken addon.

I'm guessing the issue may be with the fact that you are still manually configuring the broker in configuration.yaml.  On current versions of Home Assistant this isn't typically required as you can configure everything via the Web UI and this provides an MQTT service API which the addon attempts to use to automatically configure everything without user intervention.

In 4.0.0 I have modified the addon to use this new services API but, unfortunately, it appears that for people that are still using the old school manual configuration for MQTT this API doesn't work.  I will probably have to release an update that allows users to manually specify their configuration again.

**Comment by tsightler** [comment] 2020-09-06 00:17
> same here the addon been running without any issue before this update. Now it doesn't even start. It give an oop out msg of "Failed to start addon
> Unkown error, see logs"
> However there nothing on the log, i mean nothing completely empty weird.

This doesn't sound at all like the problem being reported here and also, this is with the addon, not this script, so really has nothing to do with the script.  Most likely you just need to remove and reinstall the addon from scratch to solve this problem as it's already been reported that, for reasons unknown at this point, some systems fail to pull the updated docker image during the upgrade (I don't have any idea how this could be as this is not handled by the addon at all).

**Comment by tsightler** [comment] 2020-09-06 00:19
I'm going to close this issue as it's basically just a duplicate of the issue below and involves the addon, not this script.  Please feel free to participate and follow the issue below for resolution:
https://github.com/tsightler/ring-mqtt-ha-addon/issues/15

**Closed as completed by tsightler** 2020-09-06 00:19 UTC

**Comment by Litosaragon** [comment] 2026-01-09 11:32
Hello, i 've the problem that with a Mosquitto server running in a Docker (manually configured, not with the HA add-on ) I cannot connect with ring_mqtt.

2026-01-09T11:32:08.117Z ring-mqtt Attempting to reconnect to MQTT broker...
2026-01-09T11:32:08.119Z ring-mqtt Unable to connect to MQTT broker 
2026-01-09T11:32:09.120Z ring-mqtt Attempting to reconnect to MQTT broker...
2026-01-09T11:32:09.122Z ring-mqtt Unable to connect to MQTT broker

**Comment by Litosaragon** [comment] 2026-01-09 11:33
> Hello, i 've the problem that with a Mosquitto server running in a Docker (manually configured, not with the HA add-on ) I cannot connect with ring_mqtt.
> 
> 2026-01-09T11:32:08.117Z ring-mqtt Attempting to reconnect to MQTT broker... 2026-01-09T11:32:08.119Z ring-mqtt Unable to connect to MQTT broker 2026-01-09T11:32:09.120Z ring-mqtt Attempting to reconnect to MQTT broker... 2026-01-09T11:32:09.122Z ring-mqtt Unable to connect to MQTT broker

Other Mqtt clients work correctly with host:localhost and port 1883
