### ISSUE TITLE
Ring API stopped working?

### ISSUE THREAD

**Issue by darkneo29** [tsightler/ring-mqtt#212] opened 2021-07-28 11:52 UTC
Everything has been working great then Ring stopped in Homeassistant and my Homebridge setup.  Homebridge had update to plugin that fixed API issue.  Getting same issue on homeassistant.  Here are the logs   I removed and reinstalled plugin as well and same issue.

ring-mqtt.js version 4.5.5
Node version v14.16.1
NPM version 6.14.12
git version 2.26.3
-------------------------------------------------------
Using discovered MQTT Host: core-mosquitto
Using discovered MQTT Port: 1883
Using discovered MQTT User: addons
Using discovered MQTT password: <hidden>
-------------------------------------------------------
Running ring-mqtt...
2021-07-28T11:46:44.170Z ring-mqtt Using configuration file: /data/options.json
2021-07-28T11:46:44.174Z ring-mqtt File /data/ring-state.json not found. No saved state data available.
2021-07-28T11:46:44.174Z ring-mqtt No refresh token was found in saved state file or config file.
2021-07-28T11:46:44.174Z ring-mqtt Use the web interface to generate a new token.
2021-07-28T11:47:03.477Z ring-mqtt Username/Password was accepted, waiting for 2FA code to be entered.
2021-07-28T11:47:14.699Z ring-mqtt Using configuration file: /data/options.json
2021-07-28T11:47:14.699Z ring-mqtt Using refresh token generated via web UI.
2021-07-28T11:47:14.844Z ring-mqtt Attempting connection to Ring API using generated refresh token.
2021-07-28T11:47:15.336Z ring-mqtt Response code 404 (Not Found)
2021-07-28T11:47:15.336Z ring-mqtt Unable to connect to Ring API using generated refresh token.
2021-07-28T11:47:15.336Z ring-mqtt Could not connect with saved refresh token and no refresh token exist in config file.
2021-07-28T11:47:15.336Z ring-mqtt Restart the addon to try again or use the web interface to generate a new token.

**Comment by tsightler** [comment] 2021-07-28 12:47
Ring pushed out updates yesterday which made changes to their API which broke the ability for versions <= 4.6.1 to function.  A new version was pushed last night, 4.6.2 to address this change.  I don't understand how you could have removed and reinstalled and still be on 4.5.5 as that version has been outdated for a few weeks now.

**Comment by darkneo29** [comment] 2021-07-28 12:55
Not sure.  I switched branch to latest and everything is working.

**Comment by tsightler** [comment] 2021-07-28 13:25
Very strange indeed.  Some people seem to get the update in minutes, almost too fast as a few weeks ago I had an incorrect version that was available for only 2-3 minutes and yet somehow several people managed to install it in that time, but you are still seeing 4.5.5 as the current version?  I have no idea how it's even possible.  You could trying manually selecting reload on the addon page which should force HA to update the data for all repositories.

**Comment by darkneo29** [comment] 2021-07-28 13:34
I clicked the reload button and not the updated version shows.  Very weird but glad its all working.  Appreciate the amazing support and plugin

**Comment by jacobmr** [comment] 2021-07-28 13:51
@tsightler - Thx for rapid update.  

I'm not able to go from 4.6.1 to 4.6.2 .. getting an error:  "'03cabcc9_ring_mqtt'"  (which is the hostname) ..  in red text on the updater screen. 


<img width="587" alt="Screen Shot 2021-07-28 at 9 51 11 AM" src="https://user-images.githubusercontent.com/582121/127334066-bc7e2dba-8d04-47ac-bac5-66e5cc21230c.png">

**Comment by tsightler** [comment] 2021-07-28 14:18
@jacobmr The supervisor logs on the system tab should have more information as that error is not really useful, although I would consider this a Home Assistant issue, not an issue with the addon.  Typically I've seen this caused by lack of space on the storage device.

**Comment by jacobmr** [comment] 2021-07-28 15:26
Hmm .. @tsightler .. Plenty of space.  Log below.  Advice?

--

21-07-28 08:02:01 ERROR (MainThread) [supervisor.jobs] Unhandled exception: '03cabcc9_ring_mqtt'
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 105, in wrapper
    return await self._method(*args, **kwargs)
  File "/usr/src/supervisor/supervisor/addons/__init__.py", line 265, in update
    store = self.store[slug]
KeyError: '03cabcc9_ring_mqtt'

**Comment by jacobmr** [comment] 2021-07-28 15:32
Well .. I deleted ring_mqtt snapshots (still have >800 GB free, btw) and re-attempted the upgrade with the "take snapshot" toggle off .. and the upgrade worked. Thx.  If others have this problem - perhaps it's got something to do with snapshot creation.

**Comment by tsightler** [comment] 2021-07-28 15:50
A little bit of Google searching shows that other addons also experience this on occasion:

https://community.home-assistant.io/t/update-of-esphome-to-1-20-1-fails/325194
https://githubmemory.com/repo/home-assistant/supervisor/issues/2985

Based on this, I don't think the issue is related to this addon in any way.  Seems like restarting the supervisor and retrying is the most common fix, although that first one says clearing Chrome cache which seems, well, not likely to me but who knows?

Closing this issue now.

**Closed as completed by tsightler** 2021-07-28 15:50 UTC
