### ISSUE TITLE
Cannot run ring-mqtt container > 4.7.2 on Raspberry PI 4 / Home Assistant Core

### ISSUE THREAD

**Issue by LoicRivoal** [tsightler/ring-mqtt#265] opened 2021-09-17 13:20 UTC
Running Raspbian GNU/Linux 10 (buster) and Home Assistant Core 2021.9.6
Having no issue of running ring-mqtt 4.7.2 with container, works perfectly.
Using config.json in /etc/ring-mqtt
While trying to run container for 4.8.0 4.8.1 or 4.8.2 version got the following :  

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] ring-mqtt.sh: executing...
-------------------------------------------------------
| Ring Devices via MQTT                               |
| Docker Edition                                      |
|                                                     |
| Report issues at:                                   |
| https://github.com/tsightler/ring-mqtt              |
-------------------------------------------------------
[cont-init.d] ring-mqtt.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
-------------------------------------------------------
ring-mqtt.js version: 4.8.2
Node version v14.17.6

#
# Fatal error in , line 0
# unreachable code
#
#
#
#FailureMessage Object: 0xbeb6e09c
NPM version
git version 2.32.0
-------------------------------------------------------
Running ring-mqtt...

#
# Fatal error in , line 0
# unreachable code
#
#
#
#FailureMessage Object: 0xbef8e09c
-------------------------------------------------------
ring-mqtt.js version: 4.8.2
Node version v14.17.6

**Comment by tsightler** [comment] 2021-09-17 13:50
Duplicate of #237.  This issue is related to outdated Docker in Raspbian which is unable to run newer container OS versions like Alpine 3.13 and greater (and several others) due to improper handling of a system call to time64.  The 4.8.x branch switched to Alpine 3.14.x for it's base due to some updated dependencies required for streaming support.  Now that rtsp-simple-server has a binary release that includes the fixes I needed, I could probably revert to Alpine 3.12 but that platform has only about 6 months of support lifetime left so reverting at this point seems like only a very short term fix.

There are several workarounds available in that thread, but IMO, the best is to update docker and it's dependent libraries, however, any of them should be good enough to get you running again.

**Closed as completed by tsightler** 2021-09-17 13:50 UTC
Labels: duplicate

**Comment by LoicRivoal** [comment] 2021-09-17 14:16
Thanks, applied the workaround from #237 and it works now.
