### ISSUE TITLE
Intercom geht seid update nicht mehr

### ISSUE THREAD

**Issue by jeff1975** [tsightler/ring-mqtt#661] opened 2023-07-02 07:28 UTC
2023-07-02T07:22:18.565Z ring-mqtt ERROR - Uncaught Exception
2023-07-02T07:22:18.568Z ring-mqtt Cannot read properties of undefined (reading 'toString')
2023-07-02T07:22:18.610Z ring-mqtt TypeError: Cannot read properties of undefined (reading 'toString')
    at removeTopicAliasAndRecoverTopicName (/app/ring-mqtt/node_modules/mqtt/lib/client.js:150:28)
    at storeAndSend (/app/ring-mqtt/node_modules/mqtt/lib/client.js:222:11)
    at MqttClient._sendPacket (/app/ring-mqtt/node_modules/mqtt/lib/client.js:1240:7)
    at publishProc (/app/ring-mqtt/node_modules/mqtt/lib/client.js:655:14)
    at MqttClient.publish (/app/ring-mqtt/node_modules/mqtt/lib/client.js:665:74)
    at EventEmitter.<anonymous> (file:///app/ring-mqtt/lib/mqtt.js:33:25)
    at EventEmitter.emit (node:events:513:28)
    at Lock.mqttPublish (file:///app/ring-mqtt/devices/base-ring-device.js:225:21)
    at Lock.publishDingState (file:///app/ring-mqtt/devices/intercom.js:86:18)
    at Lock.publishState (file:///app/ring-mqtt/devices/intercom.js:76:14)

**Comment by tsightler** [comment] 2023-07-02 14:37
The intercom code is unchanged in recent updates so it's not clear to me how anything could have broken in an update.  Also, the error above appears to occur in just a basic state update so it's even more unclear what could be the cause of this issue.  Please provide full logs so we can see if maybe something is happening earlier, perhaps during discovery, that is triggering the issue.  If you don't want to post full logs publicly you can send them to my email, it is the same username as here at gmail, just provide a reference to this issue.

**Comment by tsightler** [comment] 2023-07-06 02:46
As it has been 4 days with no response to the request for full logs, I will ask again to please provide full and complete logs.  If there is no response, this issue will be closed in the next 48 hours.

**Comment by jeff1975** [comment] 2023-07-06 08:36
Hey,

sorry was on a business trip

protocol in the appendix

 

thanks in advance

Von: tsightler ***@***.***> 
Gesendet: Donnerstag, 6. Juli 2023 04:47
An: tsightler/ring-mqtt ***@***.***>
Cc: jeff1975 ***@***.***>; Author ***@***.***>
Betreff: Re: [tsightler/ring-mqtt] Intercom geht seid update nicht mehr (Issue #661)

 

As it has been 4 days with no response to the request for full logs, I will ask again to please provide full and complete logs. If there is no response, this issue will be closed in the next 48 hours.

**Comment by tsightler** [comment] 2023-07-06 13:01
Apologies, but I don't see anything attached anywhere.  I have at least a hint of what might be the issue based on the above, but I need full logs to verify.  You can send logs directly to tsightler at gmail if you like.

**Comment by tsightler** [comment] 2023-07-10 15:17
As this issue has been opened for a week and I still haven't received full logs I'm forced to close it for now.  If you do get an opportunity to provide logs, we can re-open.  Unfortunately, without full logs it's really difficult to understand what might be happening here.  There are some minor clues in the snippet, but not enough to be able to track it down.

**Closed as completed by tsightler** 2023-07-10 15:17 UTC
Labels: support
