### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by haruny** [tsightler/ring-mqtt#128] opened 2020-11-09 20:48 UTC
Thank you for this excellent work.
I'm interested in live viewing the cameras/doorbells.
I've found another addon that does it: https://github.com/jeroenterheerdt/ring-hassio but I don't want to have 2 addons for a single device also the other one makes me deal with tokens.

I think this would be a great feature addition to your addon. 
Thanks.

**Comment by tsightler** [comment] 2020-11-09 21:22
This is a duplicate of #121 and will be closed for the same reason as live streams are out of scope for this project as MQTT is not a platform that support streaming.

There's no reason you can't use both addons together happily and having two addons makes sense as they do two completely different things.  Improvements for token management should in ring-hassio should be directed to that project.

**Closed as completed by tsightler** 2020-11-09 21:22 UTC
