### ISSUE TITLE
4.5.6 isn’t working

### ISSUE THREAD

**Issue by j6s33m** [tsightler/ring-mqtt#190] opened 2021-07-12 14:57 UTC
Woke up to see that this updated overnight from v4.5.5 to v4.5.6 and the docker container is in nonstop restarting loop. All devices are no longer seen in Home Assistant.

**Comment by tsightler** [comment] 2021-07-12 15:06
Duplicate of #189, just reload your repos on the addon page and then "upgrade" back to 4.5.5.  The release of 4.5.6 was not intended and was only up for about 2 minutes but I guess a few systems still managed to get it.

**Comment by j6s33m** [comment] 2021-07-12 15:57
I’ve tried to revert to 4.5.5 but still having the same problem. Additionally the 4.5.6 version is still showing and pulling in docker if you keep “latest” in container pull
________________________________

**Comment by tsightler** [comment] 2021-07-12 16:04
> pulling in docker if you keep “latest” in container pull

I don't know what this means.  Yes, there is a Docker image for 4.5.6, but if you are using the addon it is still on 4.5.5 and if you simply reload the repo it will give you the option to "upgrade' to 4.5.5 no matter what version you are on (unless you already have 4.5.5) and it will pull in the 4.5.5 specific image, which hasn't changed.  It will not pull "latest" so I don't understand what this means unless you are trying to do manual things with docker, in which case, just don't pull "latest" and you'll be fine.

Worst case, just uninstall the addon and reinstall it.

**Comment by j6s33m** [comment] 2021-07-12 16:11
I’m not using addon since I’m not using Supervisor. So I have ring-mqtt set up as it’s own docker instance and even after downgrading and forcing the 4.5.5 container version, I’m still getting the infinite loop of the container restarting. This wasn’t happening before on 4.5.5 so something is still buggy.
________________________________

**Comment by tsightler** [comment] 2021-07-12 16:20
The 4.5.5 image is unchanged so I'm not sure what the problem could possibly be with it.  Even the current 4.5.6 image should be fine.  Are you sure you have purged the local image cache?  That's the only thing I can think of, but then again, you didn't post any logs so I was just assuming you managed to get unlucky and pull in the latest version during those few minutes it was broken.  Even the current 4.5.6 image should be fine.

**Comment by j6s33m** [comment] 2021-07-12 16:23
All my logs say is “running ring-mqtt…” over and over as it keeps restarting
________________________________

**Comment by tsightler** [comment] 2021-07-12 16:35
Unfortunately I don't know how to help you if that's all you are seeing in that logs as there should definitely be more than just "running ring-mqtt" since there is a full banner with version numbers and such printed before that point and the only thing that can make the process exit is an error so that should be available in the docker logs as well.  If you are not even seeing the startup banners or any errors in the log then something is seriously wrong but I can't reproduce it so I'm not sure what else I can do.

**Comment by tsightler** [comment] 2021-07-12 16:58
I did go ahead and push a fixed 4.5.6 image as well so, no matter what image, it should work.  I tested the docker image for 4.5.5 and 4.5.6 again in my setup and they both worked fine so I'm out of ideas.

**Comment by tsightler** [comment] 2021-07-12 16:59
Also, I'll re-open the issue for now since I jumped the gun assuming you were using the addon.

**Comment by tsightler** [comment] 2021-07-15 02:48
Closing this again as I've published 4.5.7 with additional fixes (not related to your issue).  If you do still have problems please feel free to open another issue and we can dig deeper.

**Closed as completed by tsightler** 2021-07-15 02:48 UTC
