### ISSUE TITLE
Bug: Latest docker build crashes with s6-overlay-suexec: not found

### ISSUE THREAD

**Issue by 3QL** [tsightler/ring-mqtt#552] opened 2023-02-11 07:55 UTC
### Describe the Bug

docker does not start

### Steps to Reproduce

Run docker build v5.1.3

### Expected Behavior

should start

### Log Output

```shell
Starting from docker-compose gives error:

# docker-compose up ring-mqtt
Recreating ring-mqtt ... done
Attaching to ring-mqtt
ring-mqtt              | /init: exec: line 37: s6-overlay-suexec: not found
```

### Config File

```shell
ring-mqtt:
    container_name: ring-mqtt
    restart: unless-stopped
    image: tsightler/ring-mqtt
#    image: 7ed73bb15eba -> previous image works
    ports:
      - 8554:8554                      # Enable RTSP port for external media player access
    network_mode: "bridge"
    #environment:
      #- DEBUG=ring-*     
    volumes:
      - /opt/ring-mqtt:/data           # Mapping of local folder to provide persistent storage
    logging:                           #limit logs to 10m and 3 files
      options:
        max-size: 10m
        max-file: "3"
```

### Install Type

Docker

### Version

v5.1.3

### Operating System

Debian

### Architecture

x86_64

### Machine Details

Physical x86_64

**Comment by tsightler** [comment] 2023-02-11 15:42
Please delete any local images and re-pull.  There was an error with the x86_64 image caused by an upstream issue with the Alpine image being incomplete.  However, I'm surprised you managed to get this image as the incorrect image was only on Docker Hub for maybe a minute before automatic testing discovered and it and it was reverted, and an updated 5.1.3 image was pushed., just a couple of minutes later.  Are you using some type of automated tool to update docker images or did you just get so unlucky as to pull an image in that minute?

**Comment by 3QL** [comment] 2023-02-11 19:23
I repulled and now it works again
I'm using watchtower, that pulls docker fast :) Somehow it did not repull again after this update, perhaps because the tag didn´t change?

**Comment by tsightler** [comment] 2023-02-11 19:46
Hmm, interesting.  I'm not sure I'd trust pulling images mere seconds after they are published as being a good idea if I'm hoping for a moderately stable environment.  It's not at all uncommon for images to be published and then pulled and republished again if an issue is discovered.

That being said, I'm not at all clear why docker considered the initial build as successful and pushed it as the upstream Alpine image was totally borked for a few hours, which just happened to coincide with the time the image was built.  It only impacted the x86_64 image.

Anyway, it's good for now so I'll close this.

**Closed as completed by tsightler** 2023-02-11 19:46 UTC
Labels: bug
